<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Missing Data and Multiple Imputation | Notes for Case Studies in Health Big Data</title>
  <meta name="description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Missing Data and Multiple Imputation | Notes for Case Studies in Health Big Data" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://nchenderson.github.io/HDS629notes/" />
  
  <meta property="og:description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  <meta name="github-repo" content="nchenderson/HDS629notes" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Missing Data and Multiple Imputation | Notes for Case Studies in Health Big Data" />
  
  <meta name="twitter:description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  

<meta name="author" content="Nicholas Henderson" />


<meta name="date" content="2021-02-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="mixed-models.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Biostat 629</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="mixed-models.html"><a href="mixed-models.html"><i class="fa fa-check"></i><b>1</b> Mixed Models for Longitudinal Data Analysis</a><ul>
<li class="chapter" data-level="1.1" data-path="mixed-models.html"><a href="mixed-models.html#sec:methods-overview"><i class="fa fa-check"></i><b>1.1</b> Methods for Analyzing Longitudinal Data</a></li>
<li class="chapter" data-level="1.2" data-path="mixed-models.html"><a href="mixed-models.html#mixed-models-for-continuous-outcomes"><i class="fa fa-check"></i><b>1.2</b> Mixed Models for Continuous Outcomes</a></li>
<li class="chapter" data-level="1.3" data-path="mixed-models.html"><a href="mixed-models.html#advantages-of-using-random-effects"><i class="fa fa-check"></i><b>1.3</b> Advantages of using random effects</a><ul>
<li class="chapter" data-level="1.3.1" data-path="mixed-models.html"><a href="mixed-models.html#within-subject-correlation"><i class="fa fa-check"></i><b>1.3.1</b> Within-subject correlation</a></li>
<li class="chapter" data-level="1.3.2" data-path="mixed-models.html"><a href="mixed-models.html#inference-about-heterogeneity---variance-of-random-effects"><i class="fa fa-check"></i><b>1.3.2</b> Inference about Heterogeneity - Variance of Random Effects</a></li>
<li class="chapter" data-level="1.3.3" data-path="mixed-models.html"><a href="mixed-models.html#best-linear-unbiased-prediction"><i class="fa fa-check"></i><b>1.3.3</b> Best Linear Unbiased Prediction</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="mixed-models.html"><a href="mixed-models.html#generalized-linear-mixed-models-glmms"><i class="fa fa-check"></i><b>1.4</b> Generalized linear mixed models (GLMMs)</a><ul>
<li class="chapter" data-level="1.4.1" data-path="mixed-models.html"><a href="mixed-models.html#glmms-with-binary-outcomes"><i class="fa fa-check"></i><b>1.4.1</b> GLMMs with Binary Outcomes</a></li>
<li class="chapter" data-level="1.4.2" data-path="mixed-models.html"><a href="mixed-models.html#glmms-with-count-outcomes"><i class="fa fa-check"></i><b>1.4.2</b> GLMMs with Count Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="mixed-models.html"><a href="mixed-models.html#fitting-linear-mixed-models-lmms-and-generalized-linear-mixed-models-glmms-in-r"><i class="fa fa-check"></i><b>1.5</b> Fitting Linear Mixed Models (LMMs) and Generalized Linear Mixed models (GLMMs) in <strong>R</strong></a><ul>
<li class="chapter" data-level="1.5.1" data-path="mixed-models.html"><a href="mixed-models.html#fitting-lmms-with-the-sleepstudy-data"><i class="fa fa-check"></i><b>1.5.1</b> Fitting LMMs with the sleepstudy data</a></li>
<li class="chapter" data-level="1.5.2" data-path="mixed-models.html"><a href="mixed-models.html#fitting-binary-glmms-using-the-ohio-data"><i class="fa fa-check"></i><b>1.5.2</b> Fitting Binary GLMMs using the Ohio data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="missing-data.html"><a href="missing-data.html"><i class="fa fa-check"></i><b>2</b> Missing Data and Multiple Imputation</a><ul>
<li class="chapter" data-level="2.1" data-path="missing-data.html"><a href="missing-data.html#missing-data-in-r-and-direct-approaches-for-handling-missing-data"><i class="fa fa-check"></i><b>2.1</b> Missing Data in R and “Direct Approaches” for Handling Missing Data</a><ul>
<li class="chapter" data-level="2.1.1" data-path="missing-data.html"><a href="missing-data.html#complete-case-analysis-listwise-deletion"><i class="fa fa-check"></i><b>2.1.1</b> Complete Case Analysis (Listwise Deletion)</a></li>
<li class="chapter" data-level="2.1.2" data-path="missing-data.html"><a href="missing-data.html#other-direct-methods"><i class="fa fa-check"></i><b>2.1.2</b> Other “Direct” Methods</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="missing-data.html"><a href="missing-data.html#multiple-imputation"><i class="fa fa-check"></i><b>2.2</b> Multiple Imputation</a><ul>
<li class="chapter" data-level="2.2.1" data-path="missing-data.html"><a href="missing-data.html#short-overview-of-multiple-imputation"><i class="fa fa-check"></i><b>2.2.1</b> Short Overview of Multiple Imputation</a></li>
<li class="chapter" data-level="2.2.2" data-path="missing-data.html"><a href="missing-data.html#multiple-imputation-with-mice"><i class="fa fa-check"></i><b>2.2.2</b> Multiple imputation with mice</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="missing-data.html"><a href="missing-data.html#what-is-mice-doing"><i class="fa fa-check"></i><b>2.3</b> What is MICE doing?</a></li>
<li class="chapter" data-level="2.4" data-path="missing-data.html"><a href="missing-data.html#longitudinal-data"><i class="fa fa-check"></i><b>2.4</b> Longitudinal Data</a></li>
<li class="chapter" data-level="2.5" data-path="missing-data.html"><a href="missing-data.html#different-missing-data-mechanisms"><i class="fa fa-check"></i><b>2.5</b> Different Missing Data Mechanisms</a><ul>
<li class="chapter" data-level="2.5.1" data-path="missing-data.html"><a href="missing-data.html#missing-completely-at-random-mcar"><i class="fa fa-check"></i><b>2.5.1</b> Missing Completely at Random (MCAR)</a></li>
<li class="chapter" data-level="2.5.2" data-path="missing-data.html"><a href="missing-data.html#missing-at-random-mar"><i class="fa fa-check"></i><b>2.5.2</b> Missing at Random (MAR)</a></li>
<li class="chapter" data-level="2.5.3" data-path="missing-data.html"><a href="missing-data.html#missing-not-at-random-mnar"><i class="fa fa-check"></i><b>2.5.3</b> Missing not at Random (MNAR)</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes for Case Studies in Health Big Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="missing-data" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Missing Data and Multiple Imputation</h1>
<ul>
<li>The book “Flexible Imputation of Missing Data” is a resource you also might find useful,
and it is available online at: <a href="https://stefvanbuuren.name/fimd/" class="uri">https://stefvanbuuren.name/fimd/</a></li>
</ul>
<div id="missing-data-in-r-and-direct-approaches-for-handling-missing-data" class="section level2">
<h2><span class="header-section-number">2.1</span> Missing Data in R and “Direct Approaches” for Handling Missing Data</h2>
<ul>
<li><p>In a wide range of datasets, it is very common to encounter missing values.</p></li>
<li><p>In <strong>R</strong>, missing values are stored as <code>NA</code>, meaning <strong>“Not Available”</strong>.</p></li>
</ul>
<hr />
<ul>
<li>For example, look at the <code>airquality</code> dataframe available in base <strong>R</strong></li>
</ul>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1"><span class="kw">data</span>(airquality)</a>
<a class="sourceLine" id="cb52-2" data-line-number="2"><span class="kw">head</span>(airquality)</a></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1    41     190  7.4   67     5   1
## 2    36     118  8.0   72     5   2
## 3    12     149 12.6   74     5   3
## 4    18     313 11.5   62     5   4
## 5    NA      NA 14.3   56     5   5
## 6    28      NA 14.9   66     5   6</code></pre>
<ul>
<li><p>You can see that the <strong>5th observation</strong> for the <code>Ozone</code> variable is missing,
and the <strong>5th and 6th observations</strong> for the <code>Solar.R</code> variable are missing.</p></li>
<li>You can use <code>is.na</code> to find which data entries have missing values.
<ul>
<li>If <code>is.na</code> returns <code>TRUE</code>, the entry is missing.</li>
<li>If <code>is.na</code> returns <code>FALSE</code>, the entry is not missing</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="kw">head</span>( <span class="kw">is.na</span>(airquality) )</a></code></pre></div>
<pre><code>##      Ozone Solar.R  Wind  Temp Month   Day
## [1,] FALSE   FALSE FALSE FALSE FALSE FALSE
## [2,] FALSE   FALSE FALSE FALSE FALSE FALSE
## [3,] FALSE   FALSE FALSE FALSE FALSE FALSE
## [4,] FALSE   FALSE FALSE FALSE FALSE FALSE
## [5,]  TRUE    TRUE FALSE FALSE FALSE FALSE
## [6,] FALSE    TRUE FALSE FALSE FALSE FALSE</code></pre>
<ul>
<li>Computing the sum of <code>is.na(airquality)</code> tells us how many missing values there are in this dataset.</li>
</ul>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1"><span class="kw">sum</span>( <span class="kw">is.na</span>(airquality) )  <span class="co">## 44 missing entries in total</span></a></code></pre></div>
<pre><code>## [1] 44</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1"><span class="kw">dim</span>( airquality )  <span class="co">## Dataset has a total of 153 x 6 = 918 entries</span></a></code></pre></div>
<pre><code>## [1] 153   6</code></pre>
<div id="complete-case-analysis-listwise-deletion" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Complete Case Analysis (Listwise Deletion)</h3>
<ul>
<li><p>Suppose we wanted to run a regression with <code>Ozone</code> as the response and <code>Solar.R</code>,
<code>Wind</code>, and <code>Temp</code> as the covariates.</p></li>
<li><p>If we do this in <strong>R</strong>, we will get the following result:</p></li>
</ul>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1">air.lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>( Ozone <span class="op">~</span><span class="st"> </span>Solar.R <span class="op">+</span><span class="st"> </span>Wind <span class="op">+</span><span class="st"> </span>Temp, <span class="dt">data =</span> airquality )</a>
<a class="sourceLine" id="cb60-2" data-line-number="2"><span class="kw">summary</span>( air.lm1 )</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Ozone ~ Solar.R + Wind + Temp, data = airquality)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -40.485 -14.219  -3.551  10.097  95.619 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -64.34208   23.05472  -2.791  0.00623 ** 
## Solar.R       0.05982    0.02319   2.580  0.01124 *  
## Wind         -3.33359    0.65441  -5.094 1.52e-06 ***
## Temp          1.65209    0.25353   6.516 2.42e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.18 on 107 degrees of freedom
##   (42 observations deleted due to missingness)
## Multiple R-squared:  0.6059,	Adjusted R-squared:  0.5948 
## F-statistic: 54.83 on 3 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
<hr />
<ul>
<li><p>How is <strong>R</strong> handling all the <strong>missing values</strong> in <code>airquality</code>.</p></li>
<li>As a default, <code>lm</code> conducts a <strong>complete case analysis</strong> (sometimes referred to as listwise deletion).
<ul>
<li>(This is the default unless you changed the default <code>na.action</code> setting with <code>options(...)</code>)</li>
</ul></li>
<li>A <strong>complete case analysis</strong> for regression will first <strong>delete all rows</strong> from the dataset if
any of the variables used from that row have a missing value.
<ul>
<li>In this example, a row will be dropped if either the value of <code>Ozone</code>, <code>Solar.R</code>, <code>Wind</code>, or <code>Temp</code>
is missing.</li>
</ul></li>
<li><p>After these observations have been deleted, the usual regression is fit to the remaining “complete” dataset.</p></li>
</ul>
<hr />
<ul>
<li>To remove <strong>all rows</strong> where there is at least one missing value, you can use
<code>na.omit</code>:</li>
</ul>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1">complete.air &lt;-<span class="st"> </span><span class="kw">na.omit</span>( airquality )</a>
<a class="sourceLine" id="cb62-2" data-line-number="2"><span class="co">## Check that there are no missing values</span></a>
<a class="sourceLine" id="cb62-3" data-line-number="3"><span class="kw">sum</span>( <span class="kw">is.na</span>(complete.air) )  <span class="co"># This should be zero</span></a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<ul>
<li>Because our regression model only uses the variables</li>
</ul>
<hr />
<ul>
<li>Let’s now fit a linear regression using the complete dataset <code>complete.air</code></li>
</ul>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1">air.lm2 &lt;-<span class="st"> </span><span class="kw">lm</span>( Ozone <span class="op">~</span><span class="st"> </span>Solar.R <span class="op">+</span><span class="st"> </span>Wind <span class="op">+</span><span class="st"> </span>Temp, <span class="dt">data =</span> complete.air )</a></code></pre></div>
<ul>
<li>The estimated regression coefficients <strong>should be the same</strong> when using
the “incomplete dataset” <code>airquality</code> as when using the “complete dataset” <code>complete.air</code></li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1"><span class="co">## The estimated regression coefficients should be the same</span></a>
<a class="sourceLine" id="cb65-2" data-line-number="2"><span class="kw">round</span>(air.lm1<span class="op">$</span>coefficients, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## (Intercept)     Solar.R        Wind        Temp 
##     -64.342       0.060      -3.334       1.652</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" data-line-number="1"><span class="kw">round</span>(air.lm2<span class="op">$</span>coefficients, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## (Intercept)     Solar.R        Wind        Temp 
##     -64.342       0.060      -3.334       1.652</code></pre>
</div>
<div id="other-direct-methods" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Other “Direct” Methods</h3>
<ul>
<li>In general, doing a <strong>complete-case analysis</strong> is <strong>not advisable</strong>.
<ul>
<li>A complete-case analysis should really only be used if you are confident that the data are missing
completely at random (MCAR).</li>
</ul></li>
</ul>
<hr />
<ul>
<li>A few other direct ways of handling missing data that you may have used or seen used in practice include:
<ol style="list-style-type: decimal">
<li><p><strong>Mean imputation</strong>. Missing values are replaced by the value of the <strong>mean</strong> of that variable.</p></li>
<li><p><strong>Regression imputation</strong>. Missing values are replaced by a regression prediction from
the values of the other variables.</p></li>
</ol></li>
</ul>
<hr />
</div>
</div>
<div id="multiple-imputation" class="section level2">
<h2><span class="header-section-number">2.2</span> Multiple Imputation</h2>
<div id="short-overview-of-multiple-imputation" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Short Overview of Multiple Imputation</h3>
<ul>
<li>To summarize, <strong>multiple imputation</strong> consists of the following steps:
<ol style="list-style-type: decimal">
<li><p>Create <span class="math inline">\(K\)</span> different “complete datasets” which contain no missing data.</p></li>
<li><p>For each of these <span class="math inline">\(K\)</span> complete datasets, compute the estimates of interest.</p></li>
<li><p>“Pool” these separate estimates to get a final estimate.</p></li>
</ol></li>
</ul>
<hr />
<ul>
<li><p>The nice thing about multiple imputation is that you can always
use your original analysis approach.</p></li>
<li><p>That is, you can just apply your original analysis method to each of the <span class="math inline">\(K\)</span> complete datasets.</p></li>
<li><p>The complicated part in multiple imputation is generating the <span class="math inline">\(K\)</span> complete datasets in a <strong>“valid”</strong> way.</p></li>
<li><p>Luckily, there are a number of <strong>R</strong> packages that implement different ways of creating
the <span class="math inline">\(K\)</span> <strong>imputed datasets</strong>.</p></li>
</ul>
</div>
<div id="multiple-imputation-with-mice" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Multiple imputation with mice</h3>
<ul>
<li>I will primarily focus on the <strong>mice</strong> package.
<ul>
<li><strong>mice</strong> stands for <strong>“Multivariate Imputation by Chained Equations”</strong></li>
</ul></li>
<li><p>The <code>mice</code> function within the <strong>mice</strong> package is the primary function
for performing <strong>multiple imputation</strong>.</p></li>
<li>To use <code>mice</code>, just use <code>mice(df)</code> where <code>df</code> is the <strong>name</strong> of the dataframe.
<ul>
<li>(Set <code>print = FALSE</code> if you don’t want it to print out the number of the iteration).</li>
<li>Choose a value of <code>seed</code> so that the results are reproducible.</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1"><span class="kw">library</span>(mice)</a>
<a class="sourceLine" id="cb69-2" data-line-number="2">imputed.airs &lt;-<span class="st"> </span><span class="kw">mice</span>(airquality, <span class="dt">print=</span><span class="ot">FALSE</span>, <span class="dt">seed=</span><span class="dv">101</span>)</a></code></pre></div>
<hr />
<ul>
<li><p>The object returned by <code>mice</code> will have a component called <code>imp</code> which is a list.</p></li>
<li>Each component of <code>imp</code> is a <strong>dataframe</strong> corresponding to a single variable in the original dataframe
<ul>
<li>This dataframe will contain the imputed values for the <strong>missing values</strong> of that variable.</li>
</ul></li>
<li><p>For example, <code>imputed.airs$imp</code> will be a <strong>list</strong> with each component of the list being
one of the variables from <code>airquality</code></p></li>
</ul>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1"><span class="kw">names</span>( imputed.airs<span class="op">$</span>imp )</a></code></pre></div>
<pre><code>## [1] &quot;Ozone&quot;   &quot;Solar.R&quot; &quot;Wind&quot;    &quot;Temp&quot;    &quot;Month&quot;   &quot;Day&quot;</code></pre>
<hr />
<ul>
<li>The <code>Ozone</code> component of <code>imputed.airs$imp</code> will be a dataframe with <strong>37 rows</strong> and <strong>5 columns</strong>.
<ul>
<li>This is because the <code>Ozone</code> variable had <strong>37 missing values</strong>, and there are <strong>5 multiple imputations</strong> (the default number in <strong>mice</strong>)</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1"><span class="kw">dim</span>(imputed.airs<span class="op">$</span>imp<span class="op">$</span>Ozone)</a></code></pre></div>
<pre><code>## [1] 37  5</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1"><span class="co">## Imputed missing ozone values across the five multiple imputations</span></a>
<a class="sourceLine" id="cb74-2" data-line-number="2"><span class="kw">head</span>(imputed.airs<span class="op">$</span>imp<span class="op">$</span>Ozone)</a></code></pre></div>
<pre><code>##     1  2  3  4  5
## 5   6  8 18  6 37
## 10 12 18 27 18 30
## 25  8 14  6 18 18
## 26 13  1 13 37 13
## 27 19 18  4 18 34
## 32 40 47 45 23 18</code></pre>
<ul>
<li><p>The <strong>row names</strong> in <code>imputed.airs$imp$Ozone</code> correspond to the index of the observation
in the original <code>airquality</code> dataframe.</p></li>
<li><p>For example, the 5th observation of the <code>Ozone</code> variable has 6 in the 1st imputation, 8 in
the 2nd imputation, 18 in the 3rd imputation, etc. ….</p></li>
</ul>
<hr />
<ul>
<li>Similarly, the <code>Solar.R</code> component of <code>imputed.airs$imp</code> will be a data frame
<ul>
<li>This is because the <code>Ozone</code> variable had <strong>7 missing values</strong>, and there are <strong>5 multiple imputations</strong>.</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" data-line-number="1"><span class="kw">dim</span>(imputed.airs<span class="op">$</span>imp<span class="op">$</span>Solar.R)</a></code></pre></div>
<pre><code>## [1] 7 5</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" data-line-number="1"><span class="co">## Imputed missing ozone values across the five multiple imputations</span></a>
<a class="sourceLine" id="cb78-2" data-line-number="2"><span class="kw">head</span>(imputed.airs<span class="op">$</span>imp<span class="op">$</span>Solar.R)</a></code></pre></div>
<pre><code>##      1   2   3   4   5
## 5  131 285 274  92 139
## 6  127 248 175 167 175
## 11  71  71 238 115 284
## 27 238   8  49 223 238
## 96 258 203 229 223 291
## 97 313 259 274  83 272</code></pre>
<ul>
<li>For example, the 5th observation of the <code>Solar.R</code> variable has 131 in the 1st imputation, 285 in
the 2nd imputation, 274 in the 3rd imputation, etc. ….</li>
</ul>
<div id="with-and-pool" class="section level4">
<h4><span class="header-section-number">2.2.2.1</span> with() and pool()</h4>
<ul>
<li><p>You could use the components of <code>imputed.airs$imp</code> to directly fit <strong>5 separate regression</strong> on the multiply imputed datasets and then average the results.</p></li>
<li><p>However, this is much easier if you just use the <strong>with</strong> function from <strong>mice</strong></p></li>
</ul>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" data-line-number="1">air.multi.imputelm &lt;-<span class="st"> </span><span class="kw">with</span>(imputed.airs, <span class="kw">lm</span>( Ozone <span class="op">~</span><span class="st"> </span>Solar.R <span class="op">+</span><span class="st"> </span>Wind <span class="op">+</span><span class="st"> </span>Temp))</a></code></pre></div>
<ul>
<li>This will produce <strong>5 different sets</strong> of estimates of the regression coefficients:</li>
</ul>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" data-line-number="1"><span class="kw">summary</span>(air.multi.imputelm)</a></code></pre></div>
<pre><code>## # A tibble: 20 x 6
##    term        estimate std.error statistic  p.value  nobs
##    &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
##  1 (Intercept) -90.3      19.1        -4.72 5.44e- 6   153
##  2 Solar.R       0.0642    0.0199      3.22 1.56e- 3   153
##  3 Wind         -2.31      0.550      -4.20 4.61e- 5   153
##  4 Temp          1.83      0.212       8.64 8.13e-15   153
##  5 (Intercept) -49.4      19.0        -2.60 1.02e- 2   153
##  6 Solar.R       0.0548    0.0196      2.79 5.92e- 3   153
##  7 Wind         -3.43      0.545      -6.28 3.44e- 9   153
##  8 Temp          1.46      0.211       6.92 1.27e-10   153
##  9 (Intercept) -56.7      19.0        -2.98 3.36e- 3   153
## 10 Solar.R       0.0646    0.0199      3.25 1.42e- 3   153
## 11 Wind         -3.22      0.546      -5.90 2.38e- 8   153
## 12 Temp          1.50      0.211       7.09 4.97e-11   153
## 13 (Intercept) -58.4      18.9        -3.09 2.41e- 3   153
## 14 Solar.R       0.0687    0.0199      3.46 7.08e- 4   153
## 15 Wind         -3.27      0.544      -6.01 1.35e- 8   153
## 16 Temp          1.57      0.210       7.50 5.33e-12   153
## 17 (Intercept) -58.9      22.2        -2.66 8.69e- 3   153
## 18 Solar.R       0.0404    0.0231      1.75 8.27e- 2   153
## 19 Wind         -3.31      0.636      -5.21 6.11e- 7   153
## 20 Temp          1.64      0.245       6.68 4.37e-10   153</code></pre>
<ul>
<li>To get the “pooled estimates and standard errors” from these 5 different sets of regression coefficients
use the <strong>pool</strong> function from <strong>mice</strong>:</li>
</ul>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" data-line-number="1"><span class="kw">summary</span>( <span class="kw">pool</span>(air.multi.imputelm) )</a></code></pre></div>
<pre><code>##          term     estimate   std.error statistic       df      p.value
## 1 (Intercept) -62.73141323 26.25695768 -2.389135 16.63162 2.903387e-02
## 2     Solar.R   0.05855766  0.02400718  2.439173 36.55628 1.969933e-02
## 3        Wind  -3.10764673  0.75290758 -4.127527 16.76039 7.227036e-04
## 4        Temp   1.60026617  0.27155700  5.892929 23.89788 4.511087e-06</code></pre>
<ul>
<li><p>The pooled <strong>“final estimates”</strong> of the regression coefficients are just the <strong>means</strong> of the estimated regression
coefficients from the 5 multiply imputed datasets.</p></li>
<li><p>The pooled <strong>standard error</strong> for the <span class="math inline">\(j^{th}\)</span> regression coefficient is given by
<span class="math display">\[\begin{equation}
(\textrm{pooled } SE_{j})^{2} = \frac{1}{K}\sum_{k=1}^{K} SE_{jk}^{2} + \frac{K+1}{K(K-1)}\sum_{k=1}^{K}(\hat{\beta}_{jk} - \bar{\hat{\beta}}_{j.})^{2}, 
\end{equation}\]</span>
where <span class="math inline">\(SE_{jk}\)</span> is the standard error for the <span class="math inline">\(j^{th}\)</span> <strong>regression coefficient</strong> from the <span class="math inline">\(k^{th}\)</span> <strong>complete dataset</strong>,
and <span class="math inline">\(\hat{\beta}_{jk}\)</span> is the estimate of <span class="math inline">\(\beta_{j}\)</span> from the <span class="math inline">\(k^{th}\)</span> complete dataset.</p></li>
</ul>
</div>
</div>
</div>
<div id="what-is-mice-doing" class="section level2">
<h2><span class="header-section-number">2.3</span> What is MICE doing?</h2>
<ul>
<li><p>Suppose we have data from <span class="math inline">\(q\)</span> variables <span class="math inline">\(Z_{i1}, \ldots, Z_{iq}\)</span>.</p></li>
<li><p>Let <span class="math inline">\(\mathbf{Z}_{mis}\)</span> denote the collection of missing observations and <span class="math inline">\(\mathbf{Z}_{obs}\)</span>
the collection of observed values, and let <span class="math inline">\(\mathbf{Z} = (\mathbf{Z}_{obs}, \mathbf{Z}_{mis})\)</span>.</p></li>
<li>The <strong>basic idea behind</strong> multiple imputation is to, in some way, generate samples <span class="math inline">\(\mathbf{Z}_{mis}^{(1)}, \ldots, \mathbf{Z}_{mis}^{(K)}\)</span> from a flexible probability model <span class="math inline">\(p(\mathbf{Z}_{mis}|\mathbf{Z}_{obs})\)</span>
<ul>
<li><span class="math inline">\(p(\mathbf{Z}_{mis}|\mathbf{Z}_{obs})\)</span> represents the conditional distribution of <span class="math inline">\(\mathbf{Z}_{mis}\)</span> given the observed <span class="math inline">\(\mathbf{Z}_{obs}\)</span>.</li>
</ul></li>
</ul>
<hr />
<ul>
<li>The parameter of interest
<span class="math display">\[\begin{eqnarray}
\hat{\theta} &amp;=&amp; E( \theta |\mathbf{Z}_{obs}  )
= \int E\Big\{ \theta \Big| \mathbf{Z}_{obs}, \mathbf{Z}_{mis} \Big\} p(\mathbf{Z}_{mis}|\mathbf{Z}_{obs}) d\mathbf{Z}_{mis} \nonumber \\ 
&amp;\approx&amp; \frac{1}{K} \sum_{k=1}^{K} E\Big\{ \theta \Big| \mathbf{Z}_{obs}, \mathbf{Z}_{mis}^{(k)} \Big\} 
\end{eqnarray}\]</span></li>
</ul>
<hr />
<ul>
<li><p>There are two main approaches for setting up a model for which you can sample <span class="math inline">\(\mathbf{Z}_{mis}\)</span> from the conditional
distribution of <span class="math inline">\(\mathbf{Z}_{mis}|\mathbf{Z}_{obs}\)</span>.</p></li>
<li>One approach is to directly specify a <strong>full joint model</strong> for <span class="math inline">\(\mathbf{Z} = (\mathbf{Z}_{mis}, \mathbf{Z}_{obs})\)</span>
<ul>
<li>For example, assume that <span class="math inline">\(\mathbf{Z}\)</span> follows a multivariate a normal distribution.</li>
</ul></li>
<li>The <strong>fully conditional specification</strong> (FCS) approach specifies the distribution of each variable <span class="math inline">\(\mathbf{Z}_{j}\)</span> conditional on the remaining variables <span class="math inline">\(\mathbf{Z}_{-j}\)</span>.
<ul>
<li>The FCS approach is the one used by <strong>mice</strong>.</li>
</ul></li>
</ul>
<hr />
<ul>
<li>With <strong>mice</strong>,</li>
</ul>
</div>
<div id="longitudinal-data" class="section level2">
<h2><span class="header-section-number">2.4</span> Longitudinal Data</h2>
<ul>
<li><p>A direct way to do multiple imputation with <strong>longitudinal data</strong> is to use mice
on the dataset stored in <strong>wide format</strong>.</p></li>
<li><p>Remember that in <strong>wide format</strong>, each row corresponds to a <strong>different individual</strong>.</p></li>
<li><p>Applying multiple imputation to the wide-format dataset can account for the fact that
observations across individuals will be <strong>correlated</strong>.</p></li>
</ul>
<hr />
<ul>
<li>Let’s look at the <strong>ohio</strong> data from the <strong>geepack</strong> package again</li>
</ul>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" data-line-number="1"><span class="kw">library</span>(geepack)</a>
<a class="sourceLine" id="cb85-2" data-line-number="2"><span class="kw">data</span>(ohio)</a>
<a class="sourceLine" id="cb85-3" data-line-number="3"><span class="kw">head</span>(ohio)</a></code></pre></div>
<pre><code>##   resp id age smoke
## 1    0  0  -2     0
## 2    0  0  -1     0
## 3    0  0   0     0
## 4    0  0   1     0
## 5    0  1  -2     0
## 6    0  1  -1     0</code></pre>
<hr />
<ul>
<li><p>The <strong>ohio</strong> dataset is in <strong>long format</strong>. We need to first convert this into <strong>wide format</strong>.</p></li>
<li>With <strong>tidyr</strong> you can convert from <strong>long to wide</strong> using <strong>spread</strong>:
<ul>
<li>(Use <strong>gather</strong> to go from <strong>wide to long</strong>)</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" data-line-number="1"><span class="kw">library</span>( tidyr )</a>
<a class="sourceLine" id="cb87-2" data-line-number="2">ohio.wide &lt;-<span class="st"> </span><span class="kw">spread</span>(ohio, <span class="dt">key=</span>age, <span class="dt">value=</span>resp)</a>
<a class="sourceLine" id="cb87-3" data-line-number="3"></a>
<a class="sourceLine" id="cb87-4" data-line-number="4"><span class="co">## Change variable names to so that ages go from 7 to 10</span></a>
<a class="sourceLine" id="cb87-5" data-line-number="5"><span class="kw">names</span>(ohio.wide) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;id&quot;</span>, <span class="st">&quot;smoke&quot;</span>, <span class="st">&quot;age7&quot;</span>, <span class="st">&quot;age8&quot;</span>, <span class="st">&quot;age9&quot;</span>, <span class="st">&quot;age10&quot;</span>)</a>
<a class="sourceLine" id="cb87-6" data-line-number="6"><span class="kw">head</span>(ohio.wide)</a></code></pre></div>
<pre><code>##   id smoke age7 age8 age9 age10
## 1  0     0    0    0    0     0
## 2  1     0    0    0    0     0
## 3  2     0    0    0    0     0
## 4  3     0    0    0    0     0
## 5  4     0    0    0    0     0
## 6  5     0    0    0    0     0</code></pre>
<ul>
<li>The variable <code>age7</code> now represents the value of <code>resp</code> at age 7,
<code>age8</code> represents the value of <code>resp</code> at age 8, etc…</li>
</ul>
<hr />
<ul>
<li><strong>reshape</strong> from base <strong>R</strong> can also be used to go from long to wide</li>
</ul>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" data-line-number="1"><span class="co"># Example of using reshape</span></a>
<a class="sourceLine" id="cb89-2" data-line-number="2"><span class="co">#ohio.wide2 &lt;- reshape(ohio, v.names=&quot;resp&quot;, idvar=&quot;id&quot;, timevar=&quot;age&quot;, direction=&quot;wide&quot;)</span></a></code></pre></div>
<hr />
<ul>
<li><p>The <strong>ohio</strong> dataset does not have any missing values.</p></li>
<li><p>Let’s introduce missing values for the variable <code>resp</code> values
by assuming that the <strong>probability</strong> of being missing is positively
related to smoking status.</p></li>
<li><p>Let <span class="math inline">\(R_{ij}\)</span> be an <strong>indicator of missingness</strong> of <code>resp</code> for individual <span class="math inline">\(i\)</span>
at the <span class="math inline">\(j^{th}\)</span> follow-up time.</p></li>
<li><p>When randomly generating missing values, we will assume that:
<span class="math display" id="eq:missingdat-ohio">\[\begin{equation}
P( R_{ij} = 1| \textrm{smoke}_{i}) 
= \begin{cases} 
0.05 &amp; \textrm{ if } \textrm{smoke}_{i} = 0 \\
0.25 &amp; \textrm{ if } \textrm{smoke}_{i} = 1
\end{cases}
\tag{2.1}
\end{equation}\]</span></p></li>
</ul>
<hr />
<ul>
<li>To generate missing values according to assumption <a href="missing-data.html#eq:missingdat-ohio">(2.1)</a>, we can use the following R code:
<ul>
<li>We will call the new data frame <code>ohio.wide.miss</code></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" data-line-number="1">ohio.wide.miss &lt;-<span class="st"> </span>ohio.wide</a>
<a class="sourceLine" id="cb90-2" data-line-number="2">m &lt;-<span class="st"> </span><span class="kw">nrow</span>(ohio.wide.miss) <span class="co">## number of individuals in study</span></a>
<a class="sourceLine" id="cb90-3" data-line-number="3"><span class="cf">for</span>(k <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>m) {</a>
<a class="sourceLine" id="cb90-4" data-line-number="4">    resp.values &lt;-<span class="st"> </span>ohio.wide[k, <span class="dv">3</span><span class="op">:</span><span class="dv">6</span>]  <span class="co"># values of resp for individual k</span></a>
<a class="sourceLine" id="cb90-5" data-line-number="5">    <span class="cf">if</span>(ohio.wide[k,<span class="dv">2</span>] <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) {  <span class="co"># if smoke = 1</span></a>
<a class="sourceLine" id="cb90-6" data-line-number="6">        Rij &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">size=</span><span class="dv">4</span>, <span class="dt">replace=</span><span class="ot">TRUE</span>, <span class="dt">prob=</span><span class="kw">c</span>(<span class="fl">0.75</span>, <span class="fl">0.25</span>))</a>
<a class="sourceLine" id="cb90-7" data-line-number="7">    } <span class="cf">else</span> { <span class="co"># if smoke = 0</span></a>
<a class="sourceLine" id="cb90-8" data-line-number="8">        Rij &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, <span class="dt">size=</span><span class="dv">4</span>, <span class="dt">replace=</span><span class="ot">TRUE</span>, <span class="dt">prob=</span><span class="kw">c</span>(<span class="fl">0.95</span>, <span class="fl">0.05</span>))</a>
<a class="sourceLine" id="cb90-9" data-line-number="9">    }</a>
<a class="sourceLine" id="cb90-10" data-line-number="10">    resp.values[Rij<span class="op">==</span><span class="dv">1</span>] &lt;-<span class="st"> </span><span class="ot">NA</span> <span class="co"># insert NA values where Rij = 1</span></a>
<a class="sourceLine" id="cb90-11" data-line-number="11">    ohio.wide.miss[k, <span class="dv">3</span><span class="op">:</span><span class="dv">6</span>] &lt;-<span class="st"> </span>resp.values</a>
<a class="sourceLine" id="cb90-12" data-line-number="12">}</a></code></pre></div>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" data-line-number="1"><span class="kw">head</span>(ohio.wide.miss, <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##    id smoke age7 age8 age9 age10
## 1   0     0    0    0   NA     0
## 2   1     0    0    0    0     0
## 3   2     0    0    0    0     0
## 4   3     0    0    0    0     0
## 5   4     0    0    0    0     0
## 6   5     0    0    0    0     0
## 7   6     0    0    0    0     0
## 8   7     0    0   NA    0     0
## 9   8     0    0    0    0     0
## 10  9     0    0    0    0     0</code></pre>
<ul>
<li><code>ohio.wide.miss</code> now has 257 missing entries</li>
</ul>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" data-line-number="1"><span class="kw">sum</span>( <span class="kw">is.na</span>(ohio.wide.miss))</a></code></pre></div>
<pre><code>## [1] 257</code></pre>
<hr />
<ul>
<li>Now, let’s use <strong>mice</strong> to create several <strong>“completed versions”</strong> of <code>ohio.wide.miss</code></li>
</ul>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" data-line-number="1">imputed.ohio &lt;-<span class="st"> </span><span class="kw">mice</span>(ohio.wide.miss, <span class="dt">print=</span><span class="ot">FALSE</span>, <span class="dt">seed=</span><span class="dv">101</span>)</a></code></pre></div>
</div>
<div id="different-missing-data-mechanisms" class="section level2">
<h2><span class="header-section-number">2.5</span> Different Missing Data Mechanisms</h2>
<div id="missing-completely-at-random-mcar" class="section level3">
<h3><span class="header-section-number">2.5.1</span> Missing Completely at Random (MCAR)</h3>
</div>
<div id="missing-at-random-mar" class="section level3">
<h3><span class="header-section-number">2.5.2</span> Missing at Random (MAR)</h3>
</div>
<div id="missing-not-at-random-mnar" class="section level3">
<h3><span class="header-section-number">2.5.3</span> Missing not at Random (MNAR)</h3>

<div id="refs" class="references">
<div>
<p>Diggle, Peter, Patrick Heagerty, Kung-Yee Liang, and Scott Zeger. 2013. <em>Analysis of Longitudinal Data</em>. Vol. 25.</p>
</div>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="mixed-models.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
