<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Missing Data and Multiple Imputation | Notes for Case Studies in Health Big Data</title>
  <meta name="description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Missing Data and Multiple Imputation | Notes for Case Studies in Health Big Data" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  <meta name="github-repo" content="nchenderson/HDS629notes" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Missing Data and Multiple Imputation | Notes for Case Studies in Health Big Data" />
  
  <meta name="twitter:description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  

<meta name="author" content="Nicholas Henderson" />


<meta name="date" content="2023-01-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="mixed-models.html"/>
<link rel="next" href="nonpar-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Biostat 629</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="mixed-models.html"><a href="mixed-models.html"><i class="fa fa-check"></i><b>1</b> Mixed Models for Longitudinal Data Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="mixed-models.html"><a href="mixed-models.html#sec:methods-overview"><i class="fa fa-check"></i><b>1.1</b> Methods for Analyzing Longitudinal Data</a></li>
<li class="chapter" data-level="1.2" data-path="mixed-models.html"><a href="mixed-models.html#mixed-models-for-continuous-outcomes"><i class="fa fa-check"></i><b>1.2</b> Mixed Models for Continuous Outcomes</a></li>
<li class="chapter" data-level="1.3" data-path="mixed-models.html"><a href="mixed-models.html#advantages-of-using-random-effects"><i class="fa fa-check"></i><b>1.3</b> Advantages of using random effects</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="mixed-models.html"><a href="mixed-models.html#within-subject-correlation"><i class="fa fa-check"></i><b>1.3.1</b> Within-subject correlation</a></li>
<li class="chapter" data-level="1.3.2" data-path="mixed-models.html"><a href="mixed-models.html#inference-about-heterogeneity---variance-of-random-effects"><i class="fa fa-check"></i><b>1.3.2</b> Inference about Heterogeneity - Variance of Random Effects</a></li>
<li class="chapter" data-level="1.3.3" data-path="mixed-models.html"><a href="mixed-models.html#best-linear-unbiased-prediction"><i class="fa fa-check"></i><b>1.3.3</b> Best Linear Unbiased Prediction</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="mixed-models.html"><a href="mixed-models.html#generalized-linear-mixed-models-glmms"><i class="fa fa-check"></i><b>1.4</b> Generalized linear mixed models (GLMMs)</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="mixed-models.html"><a href="mixed-models.html#glmms-with-binary-outcomes"><i class="fa fa-check"></i><b>1.4.1</b> GLMMs with Binary Outcomes</a></li>
<li class="chapter" data-level="1.4.2" data-path="mixed-models.html"><a href="mixed-models.html#glmms-with-count-outcomes"><i class="fa fa-check"></i><b>1.4.2</b> GLMMs with Count Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="mixed-models.html"><a href="mixed-models.html#fitting-linear-mixed-models-lmms-and-generalized-linear-mixed-models-glmms-in-r"><i class="fa fa-check"></i><b>1.5</b> Fitting Linear Mixed Models (LMMs) and Generalized Linear Mixed models (GLMMs) in <strong>R</strong></a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="mixed-models.html"><a href="mixed-models.html#fitting-lmms-with-the-sleepstudy-data"><i class="fa fa-check"></i><b>1.5.1</b> Fitting LMMs with the sleepstudy data</a></li>
<li class="chapter" data-level="1.5.2" data-path="mixed-models.html"><a href="mixed-models.html#model-comparison-of-lmms-using-anova"><i class="fa fa-check"></i><b>1.5.2</b> Model Comparison of LMMs using anova</a></li>
<li class="chapter" data-level="1.5.3" data-path="mixed-models.html"><a href="mixed-models.html#extracting-blups-in-lme4"><i class="fa fa-check"></i><b>1.5.3</b> Extracting BLUPs in lme4</a></li>
<li class="chapter" data-level="1.5.4" data-path="mixed-models.html"><a href="mixed-models.html#fitting-binary-glmms-using-the-ohio-data"><i class="fa fa-check"></i><b>1.5.4</b> Fitting Binary GLMMs using the Ohio data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="missing-data.html"><a href="missing-data.html"><i class="fa fa-check"></i><b>2</b> Missing Data and Multiple Imputation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="missing-data.html"><a href="missing-data.html#missing-data-in-r-and-direct-approaches-for-handling-missing-data"><i class="fa fa-check"></i><b>2.1</b> Missing Data in R and “Direct Approaches” for Handling Missing Data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="missing-data.html"><a href="missing-data.html#complete-case-analysis-listwise-deletion"><i class="fa fa-check"></i><b>2.1.1</b> Complete Case Analysis (Listwise Deletion)</a></li>
<li class="chapter" data-level="2.1.2" data-path="missing-data.html"><a href="missing-data.html#other-direct-methods"><i class="fa fa-check"></i><b>2.1.2</b> Other “Direct” Methods</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="missing-data.html"><a href="missing-data.html#multiple-imputation"><i class="fa fa-check"></i><b>2.2</b> Multiple Imputation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="missing-data.html"><a href="missing-data.html#short-overview-of-multiple-imputation"><i class="fa fa-check"></i><b>2.2.1</b> Short Overview of Multiple Imputation</a></li>
<li class="chapter" data-level="2.2.2" data-path="missing-data.html"><a href="missing-data.html#multiple-imputation-with-mice"><i class="fa fa-check"></i><b>2.2.2</b> Multiple imputation with mice</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="missing-data.html"><a href="missing-data.html#what-is-mice-doing"><i class="fa fa-check"></i><b>2.3</b> What is MICE doing?</a></li>
<li class="chapter" data-level="2.4" data-path="missing-data.html"><a href="missing-data.html#longitudinal-data"><i class="fa fa-check"></i><b>2.4</b> Longitudinal Data</a></li>
<li class="chapter" data-level="2.5" data-path="missing-data.html"><a href="missing-data.html#different-missing-data-mechanisms"><i class="fa fa-check"></i><b>2.5</b> Different Missing Data Mechanisms</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="missing-data.html"><a href="missing-data.html#missing-completely-at-random-mcar"><i class="fa fa-check"></i><b>2.5.1</b> Missing Completely at Random (MCAR)</a></li>
<li class="chapter" data-level="2.5.2" data-path="missing-data.html"><a href="missing-data.html#missing-at-random-mar"><i class="fa fa-check"></i><b>2.5.2</b> Missing at Random (MAR)</a></li>
<li class="chapter" data-level="2.5.3" data-path="missing-data.html"><a href="missing-data.html#missing-not-at-random-mnar"><i class="fa fa-check"></i><b>2.5.3</b> Missing not at Random (MNAR)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="nonpar-regression.html"><a href="nonpar-regression.html"><i class="fa fa-check"></i><b>3</b> Nonparametric Regression with Longitudinal Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="nonpar-regression.html"><a href="nonpar-regression.html#notation"><i class="fa fa-check"></i><b>3.1</b> Notation</a></li>
<li class="chapter" data-level="3.2" data-path="nonpar-regression.html"><a href="nonpar-regression.html#kernel-smoothing"><i class="fa fa-check"></i><b>3.2</b> Kernel Smoothing</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="nonpar-regression.html"><a href="nonpar-regression.html#description-of-kernel-regression"><i class="fa fa-check"></i><b>3.2.1</b> Description of Kernel Regression</a></li>
<li class="chapter" data-level="3.2.2" data-path="nonpar-regression.html"><a href="nonpar-regression.html#kernel-regression-in-the-sleepstudy-data"><i class="fa fa-check"></i><b>3.2.2</b> Kernel Regression in the sleepstudy data</a></li>
<li class="chapter" data-level="3.2.3" data-path="nonpar-regression.html"><a href="nonpar-regression.html#bandwidth-selection"><i class="fa fa-check"></i><b>3.2.3</b> Bandwidth Selection</a></li>
<li class="chapter" data-level="3.2.4" data-path="nonpar-regression.html"><a href="nonpar-regression.html#another-example-the-bone-data"><i class="fa fa-check"></i><b>3.2.4</b> Another Example: The Bone Data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="nonpar-regression.html"><a href="nonpar-regression.html#regression-splines"><i class="fa fa-check"></i><b>3.3</b> Regression Splines</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="nonpar-regression.html"><a href="nonpar-regression.html#overview"><i class="fa fa-check"></i><b>3.3.1</b> Overview</a></li>
<li class="chapter" data-level="3.3.2" data-path="nonpar-regression.html"><a href="nonpar-regression.html#regression-splines-with-longitudinal-data-in-r"><i class="fa fa-check"></i><b>3.3.2</b> Regression Splines with Longitudinal Data in R</a></li>
<li class="chapter" data-level="3.3.3" data-path="nonpar-regression.html"><a href="nonpar-regression.html#looking-at-a-continuous-and-a-binary-covariate"><i class="fa fa-check"></i><b>3.3.3</b> Looking at a Continuous and a Binary Covariate</a></li>
<li class="chapter" data-level="3.3.4" data-path="nonpar-regression.html"><a href="nonpar-regression.html#model-comparison"><i class="fa fa-check"></i><b>3.3.4</b> Model Comparison</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="glmm-lasso.html"><a href="glmm-lasso.html"><i class="fa fa-check"></i><b>4</b> Sparse Regression for Longitudinal Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="glmm-lasso.html"><a href="glmm-lasso.html#sparse-regression-methods"><i class="fa fa-check"></i><b>4.1</b> Sparse regression methods</a></li>
<li class="chapter" data-level="4.2" data-path="glmm-lasso.html"><a href="glmm-lasso.html#the-lasso-with-longitudinal-data"><i class="fa fa-check"></i><b>4.2</b> The Lasso with longitudinal data</a></li>
<li class="chapter" data-level="4.3" data-path="glmm-lasso.html"><a href="glmm-lasso.html#lasso-for-lmms-and-glmms-in-r"><i class="fa fa-check"></i><b>4.3</b> Lasso for LMMs and GLMMs in R</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="glmm-lasso.html"><a href="glmm-lasso.html#soccer-data"><i class="fa fa-check"></i><b>4.3.1</b> Soccer Data</a></li>
<li class="chapter" data-level="4.3.2" data-path="glmm-lasso.html"><a href="glmm-lasso.html#choosing-the-tuning-parameter-for-the-soccer-data"><i class="fa fa-check"></i><b>4.3.2</b> Choosing the tuning parameter for the soccer data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="glmm-lasso.html"><a href="glmm-lasso.html#cross-validation-for-longitudinal-data"><i class="fa fa-check"></i><b>4.4</b> Cross-Validation for Longitudinal Data</a></li>
<li class="chapter" data-level="4.5" data-path="glmm-lasso.html"><a href="glmm-lasso.html#penalized-generalized-estimating-equations"><i class="fa fa-check"></i><b>4.5</b> Penalized Generalized Estimating Equations</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="glmm-lasso.html"><a href="glmm-lasso.html#the-pgee-package"><i class="fa fa-check"></i><b>4.5.1</b> The PGEE package</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="glmm-lasso.html"><a href="glmm-lasso.html#glmm-lasso-with-binary-outcomes"><i class="fa fa-check"></i><b>4.6</b> GLMM-Lasso with Binary Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="risk-prediction.html"><a href="risk-prediction.html"><i class="fa fa-check"></i><b>5</b> Risk Prediction and Validation (Part I)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="risk-prediction.html"><a href="risk-prediction.html#risk-predictionstratification"><i class="fa fa-check"></i><b>5.1</b> Risk Prediction/Stratification</a></li>
<li class="chapter" data-level="5.2" data-path="risk-prediction.html"><a href="risk-prediction.html#area-under-the-roc-curve-and-the-c-statistic"><i class="fa fa-check"></i><b>5.2</b> Area under the ROC curve and the C-statistic</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="risk-prediction.html"><a href="risk-prediction.html#sensitivity-and-specificity"><i class="fa fa-check"></i><b>5.2.1</b> Sensitivity and Specificity</a></li>
<li class="chapter" data-level="5.2.2" data-path="risk-prediction.html"><a href="risk-prediction.html#the-roc-curve"><i class="fa fa-check"></i><b>5.2.2</b> The ROC curve</a></li>
<li class="chapter" data-level="5.2.3" data-path="risk-prediction.html"><a href="risk-prediction.html#computing-the-roc-curve"><i class="fa fa-check"></i><b>5.2.3</b> Computing the ROC curve</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="risk-prediction.html"><a href="risk-prediction.html#area-under-the-roc-curve"><i class="fa fa-check"></i><b>5.3</b> Area under the ROC curve</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="risk-prediction.html"><a href="risk-prediction.html#rewriting-the-formula-for-the-auc"><i class="fa fa-check"></i><b>5.3.1</b> Rewriting the formula for the AUC</a></li>
<li class="chapter" data-level="5.3.2" data-path="risk-prediction.html"><a href="risk-prediction.html#interpreting-the-auc"><i class="fa fa-check"></i><b>5.3.2</b> Interpreting the AUC</a></li>
<li class="chapter" data-level="5.3.3" data-path="risk-prediction.html"><a href="risk-prediction.html#computing-the-auc-in-r"><i class="fa fa-check"></i><b>5.3.3</b> Computing the AUC in R</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="risk-prediction.html"><a href="risk-prediction.html#calibration"><i class="fa fa-check"></i><b>5.4</b> Calibration</a></li>
<li class="chapter" data-level="5.5" data-path="risk-prediction.html"><a href="risk-prediction.html#longitudinal-data-and-risk-score-validation"><i class="fa fa-check"></i><b>5.5</b> Longitudinal Data and Risk Score Validation</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="risk-prediction2.html"><a href="risk-prediction2.html"><i class="fa fa-check"></i><b>6</b> Risk Prediction and Validation (Part II)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="risk-prediction2.html"><a href="risk-prediction2.html#the-brier-score"><i class="fa fa-check"></i><b>6.1</b> The Brier Score</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="risk-prediction2.html"><a href="risk-prediction2.html#brier-scores-for-biopsy-data"><i class="fa fa-check"></i><b>6.1.1</b> Brier scores for biopsy data</a></li>
<li class="chapter" data-level="6.1.2" data-path="risk-prediction2.html"><a href="risk-prediction2.html#out-of-sample-comparisons"><i class="fa fa-check"></i><b>6.1.2</b> Out-of-sample comparisons</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="risk-prediction2.html"><a href="risk-prediction2.html#brier-scores-with-longitudinal-data"><i class="fa fa-check"></i><b>6.2</b> Brier Scores with Longitudinal Data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="risk-prediction2.html"><a href="risk-prediction2.html#option-1"><i class="fa fa-check"></i><b>6.2.1</b> Option 1</a></li>
<li class="chapter" data-level="6.2.2" data-path="risk-prediction2.html"><a href="risk-prediction2.html#option-2"><i class="fa fa-check"></i><b>6.2.2</b> Option 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ordinal-regression.html"><a href="ordinal-regression.html"><i class="fa fa-check"></i><b>7</b> Ordinal Regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ordinal-regression.html"><a href="ordinal-regression.html#ordinal-logistic-regression"><i class="fa fa-check"></i><b>7.1</b> Ordinal Logistic Regression</a></li>
<li class="chapter" data-level="7.2" data-path="ordinal-regression.html"><a href="ordinal-regression.html#ordinal-regression-details"><i class="fa fa-check"></i><b>7.2</b> Ordinal Regression Details</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ordinal-regression.html"><a href="ordinal-regression.html#ordinal-logistic-regression-in-r"><i class="fa fa-check"></i><b>7.2.1</b> Ordinal Logistic Regression in R</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ordinal-regression.html"><a href="ordinal-regression.html#generalized-estimating-equations"><i class="fa fa-check"></i><b>7.3</b> Generalized Estimating Equations</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ordinal-regression.html"><a href="ordinal-regression.html#using-geepack-and-ordgee"><i class="fa fa-check"></i><b>7.3.1</b> Using geepack and ordgee</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ordinal-regression.html"><a href="ordinal-regression.html#penalized-regression-with-ordinal-outcomes"><i class="fa fa-check"></i><b>7.4</b> Penalized Regression with Ordinal Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="extra-topics.html"><a href="extra-topics.html"><i class="fa fa-check"></i><b>8</b> Extra Topics</a>
<ul>
<li class="chapter" data-level="8.1" data-path="extra-topics.html"><a href="extra-topics.html#uncertainty-in-variable-importance-measures"><i class="fa fa-check"></i><b>8.1</b> Uncertainty in Variable Importance Measures</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="extra-topics.html"><a href="extra-topics.html#subsampling-for-random-forest-vimp-scores"><i class="fa fa-check"></i><b>8.1.1</b> Subsampling for Random Forest VIMP scores</a></li>
<li class="chapter" data-level="8.1.2" data-path="extra-topics.html"><a href="extra-topics.html#stability-selection-for-penalized-regression"><i class="fa fa-check"></i><b>8.1.2</b> Stability Selection for Penalized Regression</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes for Case Studies in Health Big Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="missing-data" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Missing Data and Multiple Imputation<a href="missing-data.html#missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<ul>
<li>The book “Flexible Imputation of Missing Data” is a resource you also might find useful. It is available online at: <a href="https://stefvanbuuren.name/fimd/" class="uri">https://stefvanbuuren.name/fimd/</a></li>
</ul>
<div id="missing-data-in-r-and-direct-approaches-for-handling-missing-data" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Missing Data in R and “Direct Approaches” for Handling Missing Data<a href="missing-data.html#missing-data-in-r-and-direct-approaches-for-handling-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>In many real-world datasets, it is very common to have missing values.</p></li>
<li><p>In <strong>R</strong>, missing values are stored as <code>NA</code>, meaning <strong>“Not Available”</strong>.</p></li>
</ul>
<hr />
<ul>
<li>As an example, let’s look at the <code>airquality</code> dataframe available in base <strong>R</strong></li>
</ul>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="missing-data.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(airquality)</span>
<span id="cb58-2"><a href="missing-data.html#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airquality)</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1    41     190  7.4   67     5   1
## 2    36     118  8.0   72     5   2
## 3    12     149 12.6   74     5   3
## 4    18     313 11.5   62     5   4
## 5    NA      NA 14.3   56     5   5
## 6    28      NA 14.9   66     5   6</code></pre>
<ul>
<li><p>You can see that the <strong>5th observation</strong> for the <code>Ozone</code> variable is missing,
and the <strong>5th and 6th observations</strong> for the <code>Solar.R</code> variable are missing.</p></li>
<li><p>You can use <code>is.na</code> to find which data entries have missing values.</p>
<ul>
<li>If <code>is.na</code> returns <code>TRUE</code>, the entry is missing.</li>
<li>If <code>is.na</code> returns <code>FALSE</code>, the entry is not missing</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="missing-data.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>( <span class="fu">is.na</span>(airquality) )</span></code></pre></div>
<pre><code>##      Ozone Solar.R  Wind  Temp Month   Day
## [1,] FALSE   FALSE FALSE FALSE FALSE FALSE
## [2,] FALSE   FALSE FALSE FALSE FALSE FALSE
## [3,] FALSE   FALSE FALSE FALSE FALSE FALSE
## [4,] FALSE   FALSE FALSE FALSE FALSE FALSE
## [5,]  TRUE    TRUE FALSE FALSE FALSE FALSE
## [6,] FALSE    TRUE FALSE FALSE FALSE FALSE</code></pre>
<ul>
<li>Computing the sum of <code>is.na(airquality)</code> tells us how many missing values there are in this dataset.</li>
</ul>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="missing-data.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( <span class="fu">is.na</span>(airquality) )  <span class="do">## 44 missing entries in total</span></span></code></pre></div>
<pre><code>## [1] 44</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="missing-data.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>( airquality )  <span class="do">## Dataset has a total of 153 x 6 = 918 entries</span></span></code></pre></div>
<pre><code>## [1] 153   6</code></pre>
<ul>
<li>Doing <code>apply(is.na(airquality), 2, sum)</code> gives us the number of missing values for each variable.</li>
</ul>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="missing-data.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>( <span class="fu">is.na</span>(airquality), <span class="dv">2</span>, sum)</span></code></pre></div>
<pre><code>##   Ozone Solar.R    Wind    Temp   Month     Day 
##      37       7       0       0       0       0</code></pre>
<div id="complete-case-analysis-listwise-deletion" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Complete Case Analysis (Listwise Deletion)<a href="missing-data.html#complete-case-analysis-listwise-deletion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Suppose we wanted to run a regression with <code>Ozone</code> as the response and <code>Solar.R</code>,
<code>Wind</code>, and <code>Temp</code> as the covariates.</p></li>
<li><p>If we do this in <strong>R</strong>, we will get the following result:</p></li>
</ul>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="missing-data.html#cb68-1" aria-hidden="true" tabindex="-1"></a>air.lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Ozone <span class="sc">~</span> Solar.R <span class="sc">+</span> Wind <span class="sc">+</span> Temp, <span class="at">data =</span> airquality )</span>
<span id="cb68-2"><a href="missing-data.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( air.lm1 )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Ozone ~ Solar.R + Wind + Temp, data = airquality)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -40.485 -14.219  -3.551  10.097  95.619 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -64.34208   23.05472  -2.791  0.00623 ** 
## Solar.R       0.05982    0.02319   2.580  0.01124 *  
## Wind         -3.33359    0.65441  -5.094 1.52e-06 ***
## Temp          1.65209    0.25353   6.516 2.42e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.18 on 107 degrees of freedom
##   (42 observations deleted due to missingness)
## Multiple R-squared:  0.6059, Adjusted R-squared:  0.5948 
## F-statistic: 54.83 on 3 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
<hr />
<ul>
<li><p>How is <strong>R</strong> handling all the <strong>missing values</strong> in <code>airquality</code>?</p></li>
<li><p>As a default, <code>lm</code> performs a <strong>complete case analysis</strong> (sometimes referred to as listwise deletion).</p>
<ul>
<li>(This is the default unless you changed the default <code>na.action</code> setting with <code>options(...)</code>)</li>
</ul></li>
<li><p>A <strong>complete case analysis</strong> for regression will <strong>delete a rows</strong> from the dataset if
<strong>any</strong> of the variables used from that row have a missing value.</p>
<ul>
<li>In this example, a row will be dropped if either the value of <code>Ozone</code>, <code>Solar.R</code>, <code>Wind</code>, or <code>Temp</code>
is missing.</li>
</ul></li>
<li><p>After these observations have been deleted, the usual regression parameters are estimated from the remaining <strong>“complete” dataset</strong>.</p></li>
</ul>
<hr />
<ul>
<li>To remove <strong>all rows</strong> where there is at least one missing value, you can use
<code>na.omit</code>:</li>
</ul>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="missing-data.html#cb70-1" aria-hidden="true" tabindex="-1"></a>complete.air <span class="ot">&lt;-</span> <span class="fu">na.omit</span>( airquality )</span>
<span id="cb70-2"><a href="missing-data.html#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Check that there are no missing values</span></span>
<span id="cb70-3"><a href="missing-data.html#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( <span class="fu">is.na</span>(complete.air) )  <span class="co"># This should be zero</span></span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<!--* Because our regression model only uses the variables `Ozone`, `Solar.R`, `Wind`, and `Temp`,
we -->
<hr />
<ul>
<li>Let’s now fit a linear regression using the complete dataset <code>complete.air</code></li>
</ul>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="missing-data.html#cb72-1" aria-hidden="true" tabindex="-1"></a>air.lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>( Ozone <span class="sc">~</span> Solar.R <span class="sc">+</span> Wind <span class="sc">+</span> Temp, <span class="at">data =</span> complete.air )</span></code></pre></div>
<ul>
<li>Because <strong>R</strong> does a complete-case analysis as default, the estimated regression coefficients <strong>should be the same</strong> when using the “incomplete dataset” <code>airquality</code> as when using the “complete dataset” <code>complete.air</code></li>
</ul>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="missing-data.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="do">## The estimated regression coefficients should be the same</span></span>
<span id="cb73-2"><a href="missing-data.html#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(air.lm1<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## (Intercept)     Solar.R        Wind        Temp 
##     -64.342       0.060      -3.334       1.652</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="missing-data.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(air.lm2<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## (Intercept)     Solar.R        Wind        Temp 
##     -64.342       0.060      -3.334       1.652</code></pre>
</div>
<div id="other-direct-methods" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Other “Direct” Methods<a href="missing-data.html#other-direct-methods" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>In general, doing a <strong>complete-case analysis</strong> is <strong>not advisable</strong>.
<ul>
<li><p>A complete-case analysis should really only be used if you are confident that the data are <strong>missing completely at random (MCAR)</strong>.</p></li>
<li><p>Roughly speaking, <strong>MCAR</strong> means that the probability of having a missing value is not related to
<strong>missing or observed</strong> values of the data.</p></li>
<li><p>Section 2.5 gives a more formal definition of MCAR.</p></li>
</ul></li>
</ul>
<hr />
<ul>
<li>A few other direct ways of handling missing data that you may have used or seen used in practice include:
<ol style="list-style-type: decimal">
<li><p><strong>Mean imputation</strong>. Missing values are replaced by the value of the <strong>mean</strong> of that variable.</p></li>
<li><p><strong>Regression imputation</strong>. Missing values are replaced by a regression prediction from
the values of the other variables.</p></li>
</ol></li>
<li>Unless the data are <strong>missing completely at random</strong> (MCAR), each of these methods will produce biased estimates of the parameters of interest and generate incorrect standard errors.</li>
</ul>
<hr />
</div>
</div>
<div id="multiple-imputation" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Multiple Imputation<a href="missing-data.html#multiple-imputation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="short-overview-of-multiple-imputation" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Short Overview of Multiple Imputation<a href="missing-data.html#short-overview-of-multiple-imputation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>To summarize, <strong>multiple imputation</strong> consists of the following steps:
<ol style="list-style-type: decimal">
<li><p>Create <span class="math inline">\(K\)</span> different <strong>“complete datasets”</strong> where each dataset contains <strong>no missing data</strong>.</p></li>
<li><p>For <strong>each</strong> of these <span class="math inline">\(K\)</span> complete datasets, compute the estimates of interest.</p></li>
<li><p><strong>“Pool”</strong> these separate estimates to get final <strong>estimates and standard errors</strong>.</p></li>
</ol></li>
</ul>
<hr />
<ul>
<li><p>The nice thing about multiple imputation is that you can always
use your <strong>original analysis approach</strong>.</p></li>
<li><p>That is, you can just apply your original analysis method to each of the <span class="math inline">\(K\)</span> <strong>complete datasets</strong>.</p></li>
<li><p>The complicated part in multiple imputation is generating the <span class="math inline">\(K\)</span> complete datasets in a <strong>“valid”</strong> or
<strong>“statistically principled”</strong> way.</p></li>
<li><p>Fortunately, there are a number of <strong>R</strong> packages that implement different approaches for creating
the <span class="math inline">\(K\)</span> <strong>imputed datasets</strong>.</p></li>
</ul>
</div>
<div id="multiple-imputation-with-mice" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Multiple imputation with mice<a href="missing-data.html#multiple-imputation-with-mice" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>I will primarily focus on the <strong>mice</strong> package.</p>
<ul>
<li><strong>mice</strong> stands for <strong>“Multivariate Imputation by Chained Equations”</strong></li>
</ul></li>
<li><p>The <code>mice</code> function within the <strong>mice</strong> package is the primary function
for performing <strong>multiple imputation</strong>.</p></li>
<li><p>To use <code>mice</code>, just use <code>mice(df)</code> where <code>df</code> is the <strong>name</strong> of the dataframe.</p>
<ul>
<li>(Set <code>print = FALSE</code> if you don’t want it to print out the number of the iteration).</li>
<li>Choose a value of <code>seed</code> so that the results are reproducible.</li>
<li>Note that the <strong>default number</strong> of complete datasets returned is 5. This can be changed with the <code>m</code> argument. A value of <code>m</code> set to 5 or 10 is a typically recommendation for something that works well in practice.</li>
</ul></li>
<li><p>Let’s try running the <code>mice</code> function with the <code>airquality</code> dataset.</p></li>
</ul>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="missing-data.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb77-2"><a href="missing-data.html#cb77-2" aria-hidden="true" tabindex="-1"></a>imputed.airs <span class="ot">&lt;-</span> <span class="fu">mice</span>(airquality, <span class="at">print=</span><span class="cn">FALSE</span>, <span class="at">seed=</span><span class="dv">101</span>)</span></code></pre></div>
<hr />
<ul>
<li><p>The object returned by <code>mice</code> will have a component called <code>imp</code> which is a list.</p></li>
<li><p>Each component of <code>imp</code> is a <strong>dataframe</strong> corresponding to a single variable in the original dataframe</p>
<ul>
<li>This dataframe will contain the <strong>imputed values</strong> for the <strong>missing values</strong> of that variable.</li>
</ul></li>
<li><p>For example, <code>imputed.airs$imp</code> will be a <strong>list</strong> with each component of the list being
one of the variables from <code>airquality</code></p></li>
</ul>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="missing-data.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>( imputed.airs<span class="sc">$</span>imp )</span></code></pre></div>
<pre><code>## [1] &quot;Ozone&quot;   &quot;Solar.R&quot; &quot;Wind&quot;    &quot;Temp&quot;    &quot;Month&quot;   &quot;Day&quot;</code></pre>
<hr />
<ul>
<li>The <code>Ozone</code> component of <code>imputed.airs$imp</code> will be a dataframe with <strong>37 rows</strong> and <strong>5 columns</strong>.
<ul>
<li>This is because the <code>Ozone</code> variable had <strong>37 missing values</strong>, and there are <strong>5 multiple imputations</strong> (the default number in <strong>mice</strong>)</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="missing-data.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(imputed.airs<span class="sc">$</span>imp<span class="sc">$</span>Ozone)</span></code></pre></div>
<pre><code>## [1] 37  5</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="missing-data.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Imputed missing ozone values across the five multiple imputations</span></span>
<span id="cb82-2"><a href="missing-data.html#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(imputed.airs<span class="sc">$</span>imp<span class="sc">$</span>Ozone)</span></code></pre></div>
<pre><code>##     1  2  3  4  5
## 5   6  8 18  6 37
## 10 12 18 27 18 30
## 25  8 14  6 18 18
## 26 13  1 13 37 13
## 27 19 18  4 18 34
## 32 40 47 45 23 18</code></pre>
<ul>
<li><p>The <strong>row names</strong> in <code>imputed.airs$imp$Ozone</code> correspond to the index of the observation
in the original <code>airquality</code> dataframe.</p></li>
<li><p>For example, the 5th observation of the <code>Ozone</code> variable has 6 in the 1st imputation, 8 in
the 2nd imputation, 18 in the 3rd imputation, etc. ….</p></li>
</ul>
<hr />
<ul>
<li>Similarly, the <code>Solar.R</code> component of <code>imputed.airs$imp</code> will be a data frame
<ul>
<li>This is because the <code>Solar.R</code> variable had <strong>7 missing values</strong>, and there are <strong>5 multiple imputations</strong>.</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="missing-data.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(imputed.airs<span class="sc">$</span>imp<span class="sc">$</span>Solar.R)</span></code></pre></div>
<pre><code>## [1] 7 5</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="missing-data.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Imputed missing ozone values across the five multiple imputations</span></span>
<span id="cb86-2"><a href="missing-data.html#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(imputed.airs<span class="sc">$</span>imp<span class="sc">$</span>Solar.R)</span></code></pre></div>
<pre><code>##      1   2   3   4   5
## 5  131 285 274  92 139
## 6  127 248 175 167 175
## 11  71  71 238 115 284
## 27 238   8  49 223 238
## 96 258 203 229 223 291
## 97 313 259 274  83 272</code></pre>
<ul>
<li>For example, the 5th observation of the <code>Solar.R</code> variable has 131 in the 1st imputation, 285 in
the 2nd imputation, 274 in the 3rd imputation, etc. ….</li>
</ul>
<div id="with-pool-complete" class="section level4 hasAnchor" number="2.2.2.1">
<h4><span class="header-section-number">2.2.2.1</span> with(), pool(), complete()<a href="missing-data.html#with-pool-complete" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p>You could use the components of <code>imputed.airs$imp</code> to directly fit <strong>5 separate regression</strong> on the multiply imputed datasets and then average the results.</p></li>
<li><p>However, this is much easier if you just use the <strong>with</strong> function from <strong>mice</strong></p></li>
</ul>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="missing-data.html#cb88-1" aria-hidden="true" tabindex="-1"></a>air.multi.imputelm <span class="ot">&lt;-</span> <span class="fu">with</span>(imputed.airs, <span class="fu">lm</span>( Ozone <span class="sc">~</span> Solar.R <span class="sc">+</span> Wind <span class="sc">+</span> Temp))</span></code></pre></div>
<ul>
<li>This will produce <strong>5 different sets</strong> of estimates of the regression coefficients:</li>
</ul>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="missing-data.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(air.multi.imputelm)</span></code></pre></div>
<pre><code>## # A tibble: 20 × 6
##    term        estimate std.error statistic  p.value  nobs
##    &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;
##  1 (Intercept) -90.3      19.1        -4.72 5.44e- 6   153
##  2 Solar.R       0.0642    0.0199      3.22 1.56e- 3   153
##  3 Wind         -2.31      0.550      -4.20 4.61e- 5   153
##  4 Temp          1.83      0.212       8.64 8.13e-15   153
##  5 (Intercept) -49.4      19.0        -2.60 1.02e- 2   153
##  6 Solar.R       0.0548    0.0196      2.79 5.92e- 3   153
##  7 Wind         -3.43      0.545      -6.28 3.44e- 9   153
##  8 Temp          1.46      0.211       6.92 1.27e-10   153
##  9 (Intercept) -56.7      19.0        -2.98 3.36e- 3   153
## 10 Solar.R       0.0646    0.0199      3.25 1.42e- 3   153
## 11 Wind         -3.22      0.546      -5.90 2.38e- 8   153
## 12 Temp          1.50      0.211       7.09 4.97e-11   153
## 13 (Intercept) -58.4      18.9        -3.09 2.41e- 3   153
## 14 Solar.R       0.0687    0.0199      3.46 7.08e- 4   153
## 15 Wind         -3.27      0.544      -6.01 1.35e- 8   153
## 16 Temp          1.57      0.210       7.50 5.33e-12   153
## 17 (Intercept) -58.9      22.2        -2.66 8.69e- 3   153
## 18 Solar.R       0.0404    0.0231      1.75 8.27e- 2   153
## 19 Wind         -3.31      0.636      -5.21 6.11e- 7   153
## 20 Temp          1.64      0.245       6.68 4.37e-10   153</code></pre>
<ul>
<li>To get the “pooled estimates and standard errors” from these 5 different sets of regression coefficients
use the <strong>pool</strong> function from <strong>mice</strong>:</li>
</ul>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="missing-data.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( <span class="fu">pool</span>(air.multi.imputelm) )</span></code></pre></div>
<pre><code>##          term     estimate   std.error statistic       df      p.value
## 1 (Intercept) -62.73141323 26.25695768 -2.389135 16.63162 2.903387e-02
## 2     Solar.R   0.05855766  0.02400718  2.439173 36.55628 1.969933e-02
## 3        Wind  -3.10764673  0.75290758 -4.127527 16.76039 7.227036e-04
## 4        Temp   1.60026617  0.27155700  5.892929 23.89788 4.511087e-06</code></pre>
<ul>
<li><p>The pooled <strong>“final estimates”</strong> of the regression coefficients are just the <strong>means</strong> of the estimated regression
coefficients from the 5 multiply imputed datasets.</p></li>
<li><p>The pooled <strong>standard error</strong> for the <span class="math inline">\(j^{th}\)</span> regression coefficient is given by
<span class="math display">\[\begin{equation}
(\textrm{pooled } SE_{j})^{2} = \frac{1}{K}\sum_{k=1}^{K} SE_{jk}^{2} + \frac{K+1}{K(K-1)}\sum_{k=1}^{K}(\hat{\beta}_{jk} - \bar{\hat{\beta}}_{j.})^{2},
\end{equation}\]</span>
where <span class="math inline">\(SE_{jk}\)</span> is the standard error for the <span class="math inline">\(j^{th}\)</span> <strong>regression coefficient</strong> from the <span class="math inline">\(k^{th}\)</span> <strong>complete dataset</strong>,
and <span class="math inline">\(\hat{\beta}_{jk}\)</span> is the estimate of <span class="math inline">\(\beta_{j}\)</span> from the <span class="math inline">\(k^{th}\)</span> complete dataset.</p></li>
</ul>
<hr />
<ul>
<li><p>It is sometimes useful to actually <strong>extract</strong> each of the completed datasets.</p>
<ul>
<li>This is true, for example, in <strong>longitudinal data</strong> where you may want to go back and forth between <strong>“wide” and “long” formats</strong>.</li>
</ul></li>
<li><p>To extract each of the completed datasets, you can use the <code>complete</code> function from <strong>mice</strong>.</p></li>
<li><p>The following code will return the <strong>5 complete datasets</strong> from <code>imputed.airs</code></p></li>
</ul>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="missing-data.html#cb93-1" aria-hidden="true" tabindex="-1"></a>completed.airs <span class="ot">&lt;-</span> mice<span class="sc">::</span><span class="fu">complete</span>(imputed.airs, <span class="at">action=</span><span class="st">&quot;long&quot;</span>)</span></code></pre></div>
<ul>
<li><p><code>action = "long"</code> means that it will return the 5 complete datasets as one dataframe with
the individual datasets “<strong>stacked</strong> on top of each other.”</p></li>
<li><p><code>completed.airs</code> will be a dataframe that has <strong>5 times</strong> as many rows as the <code>airquality</code> data frame</p>
<ul>
<li>The variable <code>.imp</code> is an indicator of which of the 5 imputations that row corresponds to.</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="missing-data.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(completed.airs)</span></code></pre></div>
<pre><code>##   .imp .id Ozone Solar.R Wind Temp Month Day
## 1    1   1    41     190  7.4   67     5   1
## 2    1   2    36     118  8.0   72     5   2
## 3    1   3    12     149 12.6   74     5   3
## 4    1   4    18     313 11.5   62     5   4
## 5    1   5     6     131 14.3   56     5   5
## 6    1   6    28     127 14.9   66     5   6</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="missing-data.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(completed.airs)</span></code></pre></div>
<pre><code>## [1] 765   8</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="missing-data.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(airquality)</span></code></pre></div>
<pre><code>## [1] 153   6</code></pre>
<hr />
<ul>
<li>Using <code>complete.airs</code>, we can compute the multiple imputation-based estimates of the regression coefficients <strong>“by hand”</strong>
<ul>
<li>This should give us the same results as when using <code>with</code></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="missing-data.html#cb100-1" aria-hidden="true" tabindex="-1"></a>BetaMat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow=</span><span class="dv">5</span>, <span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb100-2"><a href="missing-data.html#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) {</span>
<span id="cb100-3"><a href="missing-data.html#cb100-3" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Find beta.hat from kth imputed dataset</span></span>
<span id="cb100-4"><a href="missing-data.html#cb100-4" aria-hidden="true" tabindex="-1"></a>    BetaMat[k,] <span class="ot">&lt;-</span> <span class="fu">lm</span>(Ozone <span class="sc">~</span> Solar.R <span class="sc">+</span> Wind <span class="sc">+</span> Temp, </span>
<span id="cb100-5"><a href="missing-data.html#cb100-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data=</span>completed.airs[completed.airs<span class="sc">$</span>.imp<span class="sc">==</span>k,])<span class="sc">$</span>coefficients</span>
<span id="cb100-6"><a href="missing-data.html#cb100-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb100-7"><a href="missing-data.html#cb100-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">colMeans</span>(BetaMat), <span class="dv">3</span>)  <span class="co"># compare with the results from using the &quot;with&quot; function</span></span></code></pre></div>
<pre><code>## [1] -62.731   0.059  -3.108   1.600</code></pre>
</div>
</div>
</div>
<div id="what-is-mice-doing" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> What is MICE doing?<a href="missing-data.html#what-is-mice-doing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Suppose we have data from <span class="math inline">\(q\)</span> variables <span class="math inline">\(Z_{i1}, \ldots, Z_{iq}\)</span>.</p></li>
<li><p>Let <span class="math inline">\(\mathbf{Z}_{mis}\)</span> denote the <strong>entire collection</strong> of missing observations and <span class="math inline">\(\mathbf{Z}_{obs}\)</span>
the <strong>entire collection</strong> of observed values, and let <span class="math inline">\(\mathbf{Z} = (\mathbf{Z}_{obs}, \mathbf{Z}_{mis})\)</span>.</p></li>
<li><p>Let <span class="math inline">\(\mathbf{R}\)</span> be an indicator of missingness.</p>
<ul>
<li>That is, <span class="math inline">\(R_{ij} = 1\)</span> if <span class="math inline">\(Z_{ij}\)</span> was missing and <span class="math inline">\(R_{ij} = 0\)</span> if <span class="math inline">\(Z_{ij}\)</span> was observed.</li>
</ul></li>
<li><p>The <strong>basic idea behind</strong> multiple imputation is to, in some way, generate samples <span class="math inline">\(\mathbf{Z}_{mis}^{(1)}, \ldots, \mathbf{Z}_{mis}^{(K)}\)</span> from a flexible probability model <span class="math inline">\(p(\mathbf{Z}_{mis}|\mathbf{Z}_{obs})\)</span></p>
<ul>
<li><span class="math inline">\(p(\mathbf{Z}_{mis}|\mathbf{Z}_{obs})\)</span> represents the conditional distribution of <span class="math inline">\(\mathbf{Z}_{mis}\)</span> given the observed <span class="math inline">\(\mathbf{Z}_{obs}\)</span>.</li>
</ul></li>
<li><p>The <strong>missing at random</strong> (MAR) assumption implies we only need to work with the conditional distribution <span class="math inline">\(\mathbf{Z}_{mis}|\mathbf{Z}_{obs}\)</span>.</p>
<ul>
<li>The MAR assumption implies the distribution of <span class="math inline">\(\mathbf{Z}_{mis}\)</span> given <span class="math inline">\(\mathbf{Z}_{obs}, \mathbf{R}\)</span> is the same as the distribution of <span class="math inline">\(\mathbf{Z}_{mis}\)</span> given <span class="math inline">\(\mathbf{Z}_{obs}\)</span>.</li>
</ul></li>
</ul>
<hr />
<ul>
<li>A valid estimate <span class="math inline">\(\hat{\theta}\)</span> of the parameter of interest <span class="math inline">\(\theta\)</span> can often be thought of as a posterior mean:
<ul>
<li><span class="math inline">\(\hat{\theta} = E(\theta|\mathbf{Z}_{obs}, \mathbf{R})\)</span> is the expectation of <span class="math inline">\(\theta\)</span> given the observed data values <span class="math inline">\(\mathbf{Z}_{obs}\)</span> and missingness indicators.</li>
</ul></li>
<li>Then, <span class="math inline">\(\hat{\theta}\)</span> can be expressed as:
<span class="math display">\[\begin{eqnarray}
\hat{\theta} &amp;=&amp; E( \theta |\mathbf{Z}_{obs}, \mathbf{R}  )
= \int E\Big\{ \theta \Big| \mathbf{Z}_{obs}, \mathbf{R} \mathbf{Z}_{mis} \Big\} p(\mathbf{Z}_{mis}|\mathbf{Z}_{obs}, \mathbf{R}) d\mathbf{Z}_{mis} \nonumber \\
&amp;=&amp; \int E\Big\{ \theta \Big| \mathbf{Z}_{obs}, \mathbf{R}, \mathbf{Z}_{mis} \Big\} p(\mathbf{Z}_{mis}|\mathbf{Z}_{obs} ) d\mathbf{Z}_{mis} \nonumber \\
&amp;\approx&amp; \frac{1}{K} \sum_{k=1}^{K} E\Big\{ \theta \Big| \mathbf{Z}_{obs}, \mathbf{R}, \mathbf{Z}_{mis}^{(k)} \Big\}
\end{eqnarray}\]</span></li>
</ul>
<hr />
<ul>
<li><p>For a more non-Bayesian interpretation, you can often think of an estimate <span class="math inline">\(\hat{\theta}_{full}\)</span> with no missing data (such as maximum likelihood) as the solution of an <strong>estimating equation</strong>
<span class="math display">\[\begin{equation}
U(\theta; \mathbf{Z}_{mis}, \mathbf{Z}_{obs}) = 0
\end{equation}\]</span></p></li>
<li><p>With multiple imputation, <span class="math inline">\(\hat{\theta}\)</span> is approximately finding a solution of the following
estimating equation
<span class="math display">\[\begin{equation}
\frac{1}{K} \sum_{k=1}^{K} U(\theta; \mathbf{Z}_{mis}^{(k)}, \mathbf{Z}_{obs}) \approx E\Big\{ U(\theta; \mathbf{Z}_{mis}, \mathbf{Z}_{obs}) | \mathbf{Z}_{obs}, \mathbf{R} \Big\} = 0
\end{equation}\]</span></p></li>
</ul>
<hr />
<ul>
<li><p>There are two main approaches for setting up a model for the <strong>conditional distribution</strong> of <span class="math inline">\(\mathbf{Z}_{mis}|\mathbf{Z}_{obs}\)</span>.</p></li>
<li><p>One approach is to directly specify a <strong>full joint model</strong> for <span class="math inline">\(\mathbf{Z} = (\mathbf{Z}_{mis}, \mathbf{Z}_{obs})\)</span></p>
<ul>
<li><p>For example, you could assume that <span class="math inline">\(\mathbf{Z}\)</span> follows a multivariate a normal distribution.</p></li>
<li><p>This approach is not so straightforward when you have variables of <strong>mixed type</strong>: some continuous,some
binary, some categorical, etc. …</p></li>
</ul></li>
</ul>
<hr />
<ul>
<li><p>Let the vector <span class="math inline">\(\mathbf{Z}_{j} = (Z_{1j}, \ldots, Z_{nj})\)</span> denote all the “data” (whether observed or unobserved)
from variable <span class="math inline">\(j\)</span>.</p></li>
<li><p>The <strong>fully conditional specification</strong> (FCS) approach specifies the distribution of each variable <span class="math inline">\(\mathbf{Z}_{j}\)</span> conditional on the remaining variables <span class="math inline">\(\mathbf{Z}_{-j}\)</span>.</p>
<ul>
<li>The FCS approach is the one used by <strong>mice</strong>.</li>
</ul></li>
<li><p>With the FCS approach, we assume models for <span class="math inline">\(q\)</span> different conditional distributions
<span class="math display">\[\begin{eqnarray}
p(\mathbf{Z}_{1}&amp;|&amp;\mathbf{Z}_{-1}, \boldsymbol{\eta}_{1}) \nonumber \\
p(\mathbf{Z}_{2}&amp;|&amp;\mathbf{Z}_{-2}, \boldsymbol{\eta}_{2}) \nonumber \\
&amp;\vdots&amp; \nonumber \\
p(\mathbf{Z}_{q}&amp;|&amp;\mathbf{Z}_{-q}, \boldsymbol{\eta}_{q})
\end{eqnarray}\]</span></p></li>
</ul>
<hr />
<ul>
<li><p>With <strong>mice</strong>, the parameters <span class="math inline">\(\eta_{j}\)</span> and the missing values for each variable <span class="math inline">\(\mathbf{Z}_{j,mis}\)</span> are updated <strong>one-at-a-time</strong> via a kind of <strong>Gibbs sampler</strong>.</p></li>
<li><p>All of the missing values can be imputed in <strong>one cycle</strong> of the Gibbs sampler.</p></li>
<li><p>Multiple cycles are repeated to get <strong>multiple completed datasets</strong>.</p></li>
</ul>
<hr />
<ul>
<li><p>The default model for a continuous variable <span class="math inline">\(\mathbf{Z}_{j}\)</span> is to use <strong>predictive mean matching</strong>.</p></li>
<li><p>The default model for a binary variable <span class="math inline">\(\mathbf{Z}_{j}\)</span> is <strong>logistic regression</strong>.</p></li>
<li><p>Look at the <code>defaultMethod</code> argument of <code>mice</code> and <span class="citation">Buuren and Groothuis-Oudshoorn (<a href="#ref-buuren2010" role="doc-biblioref">2010</a>)</span> for more
details about how to change these default models.</p></li>
</ul>
</div>
<div id="longitudinal-data" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Longitudinal Data<a href="missing-data.html#longitudinal-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>A direct way to do multiple imputation with <strong>longitudinal data</strong> is to use mice
on the dataset stored in <strong>wide format</strong>.</p></li>
<li><p>Remember that in <strong>wide format</strong>, each row corresponds to a <strong>different individual</strong>.</p></li>
<li><p>Applying multiple imputation to the wide-format dataset can account for the fact that
observations across individuals will be <strong>correlated</strong>.</p></li>
</ul>
<hr />
<ul>
<li>Let’s look at the <strong>ohio</strong> data from the <strong>geepack</strong> package again</li>
</ul>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="missing-data.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geepack)</span>
<span id="cb102-2"><a href="missing-data.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ohio)</span>
<span id="cb102-3"><a href="missing-data.html#cb102-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ohio)</span></code></pre></div>
<pre><code>##   resp id age smoke
## 1    0  0  -2     0
## 2    0  0  -1     0
## 3    0  0   0     0
## 4    0  0   1     0
## 5    0  1  -2     0
## 6    0  1  -1     0</code></pre>
<hr />
<ul>
<li><p>The <strong>ohio</strong> dataset is in <strong>long format</strong>. We need to first convert this into <strong>wide format</strong>.</p></li>
<li><p>With the <strong>tidyr</strong> package, you can convert from <strong>long to wide</strong> using <strong>spread</strong>:</p>
<ul>
<li>(Use <strong>gather</strong> to go from <strong>wide to long</strong>)</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="missing-data.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>( tidyr )</span>
<span id="cb104-2"><a href="missing-data.html#cb104-2" aria-hidden="true" tabindex="-1"></a>ohio.wide <span class="ot">&lt;-</span> <span class="fu">spread</span>(ohio, <span class="at">key=</span>age, <span class="at">value=</span>resp)</span>
<span id="cb104-3"><a href="missing-data.html#cb104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-4"><a href="missing-data.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Change variable names to so that ages go from 7 to 10</span></span>
<span id="cb104-5"><a href="missing-data.html#cb104-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ohio.wide) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;id&quot;</span>, <span class="st">&quot;smoke&quot;</span>, <span class="st">&quot;age7&quot;</span>, <span class="st">&quot;age8&quot;</span>, <span class="st">&quot;age9&quot;</span>, <span class="st">&quot;age10&quot;</span>)</span>
<span id="cb104-6"><a href="missing-data.html#cb104-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ohio.wide)</span></code></pre></div>
<pre><code>##   id smoke age7 age8 age9 age10
## 1  0     0    0    0    0     0
## 2  1     0    0    0    0     0
## 3  2     0    0    0    0     0
## 4  3     0    0    0    0     0
## 5  4     0    0    0    0     0
## 6  5     0    0    0    0     0</code></pre>
<ul>
<li>The variable <code>age7</code> now represents the value of <code>resp</code> at age 7,
<code>age8</code> represents the value of <code>resp</code> at age 8, etc…</li>
</ul>
<hr />
<ul>
<li><strong>reshape</strong> from base <strong>R</strong> can also be used to go from <strong>long to wide</strong></li>
</ul>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="missing-data.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example of using reshape</span></span>
<span id="cb106-2"><a href="missing-data.html#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="co">#ohio.wide2 &lt;- reshape(ohio, v.names=&quot;resp&quot;, idvar=&quot;id&quot;, timevar=&quot;age&quot;, direction=&quot;wide&quot;)</span></span></code></pre></div>
<hr />
<ul>
<li><p>The <strong>ohio</strong> dataset does not have any missing values.</p></li>
<li><p>Let’s introduce missing values for the variable <code>resp</code> values
by assuming that the <strong>probability</strong> of being missing is positively
related to smoking status.</p></li>
<li><p>Let <span class="math inline">\(R_{ij}\)</span> be an <strong>indicator of missingness</strong> of <code>resp</code> for individual <span class="math inline">\(i\)</span>
at the <span class="math inline">\(j^{th}\)</span> follow-up time.</p></li>
<li><p>When randomly generating missing values, we will assume that:
<span class="math display" id="eq:missingdat-ohio">\[\begin{equation}
P( R_{ij} = 1| \textrm{smoke}_{i})
= \begin{cases}
0.05 &amp; \textrm{ if } \textrm{smoke}_{i} = 0 \\
0.3 &amp; \textrm{ if } \textrm{smoke}_{i} = 1
\end{cases}
\tag{2.1}
\end{equation}\]</span></p></li>
</ul>
<hr />
<ul>
<li>To generate missing values according to assumption <a href="missing-data.html#eq:missingdat-ohio">(2.1)</a>, we can use the following R code:
<ul>
<li>We will call the new data frame <code>ohio.wide.miss</code></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="missing-data.html#cb107-1" aria-hidden="true" tabindex="-1"></a>ohio.wide.miss <span class="ot">&lt;-</span> ohio.wide</span>
<span id="cb107-2"><a href="missing-data.html#cb107-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">nrow</span>(ohio.wide.miss) <span class="do">## number of individuals in study</span></span>
<span id="cb107-3"><a href="missing-data.html#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>m) {</span>
<span id="cb107-4"><a href="missing-data.html#cb107-4" aria-hidden="true" tabindex="-1"></a>    resp.values <span class="ot">&lt;-</span> ohio.wide[k, <span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>]  <span class="co"># values of resp for individual k</span></span>
<span id="cb107-5"><a href="missing-data.html#cb107-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(ohio.wide[k,<span class="dv">2</span>] <span class="sc">==</span> <span class="dv">1</span>) {  <span class="co"># if smoke = 1</span></span>
<span id="cb107-6"><a href="missing-data.html#cb107-6" aria-hidden="true" tabindex="-1"></a>        Rij <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">size=</span><span class="dv">4</span>, <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.7</span>, <span class="fl">0.3</span>))</span>
<span id="cb107-7"><a href="missing-data.html#cb107-7" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> { <span class="co"># if smoke = 0</span></span>
<span id="cb107-8"><a href="missing-data.html#cb107-8" aria-hidden="true" tabindex="-1"></a>        Rij <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">size=</span><span class="dv">4</span>, <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.95</span>, <span class="fl">0.05</span>))</span>
<span id="cb107-9"><a href="missing-data.html#cb107-9" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb107-10"><a href="missing-data.html#cb107-10" aria-hidden="true" tabindex="-1"></a>    resp.values[Rij<span class="sc">==</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span> <span class="co"># insert NA values where Rij = 1</span></span>
<span id="cb107-11"><a href="missing-data.html#cb107-11" aria-hidden="true" tabindex="-1"></a>    ohio.wide.miss[k, <span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>] <span class="ot">&lt;-</span> resp.values</span>
<span id="cb107-12"><a href="missing-data.html#cb107-12" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="missing-data.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ohio.wide.miss, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    id smoke age7 age8 age9 age10
## 1   0     0    0    0   NA     0
## 2   1     0    0    0    0     0
## 3   2     0    0    0    0     0
## 4   3     0    0    0    0     0
## 5   4     0    0    0    0     0
## 6   5     0    0    0    0     0
## 7   6     0    0    0    0     0
## 8   7     0    0   NA    0     0
## 9   8     0    0    0    0     0
## 10  9     0    0    0    0     0</code></pre>
<ul>
<li><code>ohio.wide.miss</code> now has 257 missing entries</li>
</ul>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="missing-data.html#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( <span class="fu">is.na</span>(ohio.wide.miss))</span></code></pre></div>
<pre><code>## [1] 296</code></pre>
<hr />
<ul>
<li><p>Before using <strong>multiple imputation</strong> with <code>ohio.wide.miss</code>, let’s look at the regression coefficient
estimates that would be obtained with a <strong>complete case analysis</strong>.</p></li>
<li><p>To use <code>glmer</code> on the <strong>missing-data version</strong> of <code>ohio</code>, we need to first convert <code>ohio.wide.miss</code> back into <strong>long form</strong>:</p></li>
</ul>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="missing-data.html#cb112-1" aria-hidden="true" tabindex="-1"></a>ohio.miss <span class="ot">&lt;-</span> <span class="fu">gather</span>(ohio.wide.miss, age, resp, age7<span class="sc">:</span>age10)</span>
<span id="cb112-2"><a href="missing-data.html#cb112-2" aria-hidden="true" tabindex="-1"></a>ohio.miss<span class="sc">$</span>age[ohio.miss<span class="sc">$</span>age <span class="sc">==</span> <span class="st">&quot;age7&quot;</span>] <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb112-3"><a href="missing-data.html#cb112-3" aria-hidden="true" tabindex="-1"></a>ohio.miss<span class="sc">$</span>age[ohio.miss<span class="sc">$</span>age <span class="sc">==</span> <span class="st">&quot;age8&quot;</span>] <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb112-4"><a href="missing-data.html#cb112-4" aria-hidden="true" tabindex="-1"></a>ohio.miss<span class="sc">$</span>age[ohio.miss<span class="sc">$</span>age <span class="sc">==</span> <span class="st">&quot;age9&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb112-5"><a href="missing-data.html#cb112-5" aria-hidden="true" tabindex="-1"></a>ohio.miss<span class="sc">$</span>age[ohio.miss<span class="sc">$</span>age <span class="sc">==</span> <span class="st">&quot;age10&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb112-6"><a href="missing-data.html#cb112-6" aria-hidden="true" tabindex="-1"></a>ohio.miss <span class="ot">&lt;-</span> ohio.miss[<span class="fu">order</span>(ohio.miss<span class="sc">$</span>id),]  <span class="do">## sort everything according to id</span></span>
<span id="cb112-7"><a href="missing-data.html#cb112-7" aria-hidden="true" tabindex="-1"></a>ohio.miss<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(ohio.miss<span class="sc">$</span>age)</span>
<span id="cb112-8"><a href="missing-data.html#cb112-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ohio.miss)</span></code></pre></div>
<pre><code>##      id smoke age resp
## 1     0     0  -2    0
## 538   0     0  -1    0
## 1075  0     0   0   NA
## 1612  0     0   1    0
## 2     1     0  -2    0
## 539   1     0  -1    0</code></pre>
<ul>
<li>Let’s use a <strong>random intercept</strong> model as we did in our earlier discussion of generalized linear mixed models:</li>
</ul>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="missing-data.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Complete case analysis</span></span>
<span id="cb114-2"><a href="missing-data.html#cb114-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-3"><a href="missing-data.html#cb114-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb114-4"><a href="missing-data.html#cb114-4" aria-hidden="true" tabindex="-1"></a>ohio.cca <span class="ot">&lt;-</span> <span class="fu">glmer</span>(resp <span class="sc">~</span> age <span class="sc">+</span> smoke <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> ohio.miss, <span class="at">family =</span> binomial)</span>
<span id="cb114-5"><a href="missing-data.html#cb114-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-6"><a href="missing-data.html#cb114-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Now look at estimated regression coefficients for complete case analysis:</span></span>
<span id="cb114-7"><a href="missing-data.html#cb114-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(ohio.cca)), <span class="dv">4</span>)</span></code></pre></div>
<pre><code>##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  -3.8009     0.4346 -8.7459   0.0000
## age          -0.1580     0.0783 -2.0165   0.0437
## smoke         0.2333     0.3402  0.6857   0.4929</code></pre>
<hr />
<ul>
<li>Now, let’s use <strong>mice</strong> to create 10 <strong>“completed versions”</strong> of <code>ohio.wide.miss</code></li>
</ul>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="missing-data.html#cb116-1" aria-hidden="true" tabindex="-1"></a>imputed.ohio <span class="ot">&lt;-</span> <span class="fu">mice</span>(ohio.wide.miss, <span class="at">m=</span><span class="dv">10</span>, <span class="at">print=</span><span class="cn">FALSE</span>, <span class="at">seed=</span><span class="dv">101</span>)</span></code></pre></div>
<ul>
<li>For the case of <strong>longitudinal data</strong>, we probably want to actually extract each
complete dataset.
<ul>
<li>(This is because many of the analysis methods such as <code>lmer</code> assume the data is in long form).</li>
</ul></li>
<li>This can be done with the following code:</li>
</ul>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="missing-data.html#cb117-1" aria-hidden="true" tabindex="-1"></a>completed.ohio <span class="ot">&lt;-</span> mice<span class="sc">::</span><span class="fu">complete</span>(imputed.ohio, <span class="st">&quot;long&quot;</span>)</span>
<span id="cb117-2"><a href="missing-data.html#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(completed.ohio)</span></code></pre></div>
<pre><code>##   .imp .id id smoke age7 age8 age9 age10
## 1    1   1  0     0    0    0    0     0
## 2    1   2  1     0    0    0    0     0
## 3    1   3  2     0    0    0    0     0
## 4    1   4  3     0    0    0    0     0
## 5    1   5  4     0    0    0    0     0
## 6    1   6  5     0    0    0    0     0</code></pre>
<ul>
<li><code>completed.ohio</code> will be a <strong>dataframe</strong> that has <strong>10 times</strong> as many rows as the original <code>ohio.wide</code> data frame</li>
</ul>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="missing-data.html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ohio.wide)</span></code></pre></div>
<pre><code>## [1] 537   6</code></pre>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="missing-data.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(completed.ohio)</span></code></pre></div>
<pre><code>## [1] 5370    8</code></pre>
<ul>
<li>The variable <code>.imp</code> in <code>completed.ohio</code> is an indicator of which of the 10 “imputed datasets” this is from:</li>
</ul>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="missing-data.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>( completed.ohio<span class="sc">$</span>.imp ) <span class="co"># Tabulate impute indicators</span></span></code></pre></div>
<pre><code>## 
##   1   2   3   4   5   6   7   8   9  10 
## 537 537 537 537 537 537 537 537 537 537</code></pre>
<hr />
<ul>
<li>For <strong>each</strong> of the 10 complete datasets, we need to <strong>convert</strong> the wide dataset
into long form before using <code>glmer</code>:</li>
</ul>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="missing-data.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Multiple imputation-based estimates of regression coefficients </span></span>
<span id="cb125-2"><a href="missing-data.html#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="do">## for the missing version of the ohio data.</span></span>
<span id="cb125-3"><a href="missing-data.html#cb125-3" aria-hidden="true" tabindex="-1"></a>BetaMat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow=</span><span class="dv">10</span>, <span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb125-4"><a href="missing-data.html#cb125-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>) {</span>
<span id="cb125-5"><a href="missing-data.html#cb125-5" aria-hidden="true" tabindex="-1"></a>    tmp.ohio <span class="ot">&lt;-</span> completed.ohio[completed.ohio<span class="sc">$</span>.imp<span class="sc">==</span>k,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]</span>
<span id="cb125-6"><a href="missing-data.html#cb125-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb125-7"><a href="missing-data.html#cb125-7" aria-hidden="true" tabindex="-1"></a>    tmp.ohio.long <span class="ot">&lt;-</span> <span class="fu">gather</span>(tmp.ohio, age, resp, age7<span class="sc">:</span>age10)</span>
<span id="cb125-8"><a href="missing-data.html#cb125-8" aria-hidden="true" tabindex="-1"></a>    tmp.ohio.long<span class="sc">$</span>age[tmp.ohio.long<span class="sc">$</span>age <span class="sc">==</span> <span class="st">&quot;age7&quot;</span>] <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb125-9"><a href="missing-data.html#cb125-9" aria-hidden="true" tabindex="-1"></a>    tmp.ohio.long<span class="sc">$</span>age[tmp.ohio.long<span class="sc">$</span>age <span class="sc">==</span> <span class="st">&quot;age8&quot;</span>] <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb125-10"><a href="missing-data.html#cb125-10" aria-hidden="true" tabindex="-1"></a>    tmp.ohio.long<span class="sc">$</span>age[tmp.ohio.long<span class="sc">$</span>age <span class="sc">==</span> <span class="st">&quot;age9&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb125-11"><a href="missing-data.html#cb125-11" aria-hidden="true" tabindex="-1"></a>    tmp.ohio.long<span class="sc">$</span>age[tmp.ohio.long<span class="sc">$</span>age <span class="sc">==</span> <span class="st">&quot;age10&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb125-12"><a href="missing-data.html#cb125-12" aria-hidden="true" tabindex="-1"></a>    tmp.ohio.long<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(tmp.ohio.long<span class="sc">$</span>age)</span>
<span id="cb125-13"><a href="missing-data.html#cb125-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb125-14"><a href="missing-data.html#cb125-14" aria-hidden="true" tabindex="-1"></a>    ohio.tmpfit <span class="ot">&lt;-</span> <span class="fu">glmer</span>(resp <span class="sc">~</span> age <span class="sc">+</span> smoke <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> tmp.ohio.long, </span>
<span id="cb125-15"><a href="missing-data.html#cb125-15" aria-hidden="true" tabindex="-1"></a>                         <span class="at">family =</span> binomial)</span>
<span id="cb125-16"><a href="missing-data.html#cb125-16" aria-hidden="true" tabindex="-1"></a>    BetaMat[k,] <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(ohio.tmpfit))[,<span class="dv">1</span>]</span>
<span id="cb125-17"><a href="missing-data.html#cb125-17" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<ul>
<li>The <strong>multiple imputation-based</strong> estimates of the regression coefficients for
the missing version of <strong>ohio</strong> are:</li>
</ul>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="missing-data.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">colMeans</span>(BetaMat), <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] -3.5711 -0.1066  0.2865</code></pre>
<ul>
<li>Compare the above regression coefficients with those from the <strong>complete-case</strong> analysis.</li>
</ul>
</div>
<div id="different-missing-data-mechanisms" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Different Missing Data Mechanisms<a href="missing-data.html#different-missing-data-mechanisms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>For this section, we will consider the setup where we have <strong><span class="math inline">\(n\)</span> “observations” and <span class="math inline">\(q\)</span> “variables”</strong>:
denoted by <span class="math inline">\(Z_{i1}, \ldots, Z_{iq}\)</span>, for <span class="math inline">\(i = 1, \ldots, n\)</span>.</p></li>
<li><p>Let <span class="math inline">\(\mathbf{Z}_{mis}\)</span> denote the collection of missing observations and <span class="math inline">\(\mathbf{Z}_{obs}\)</span>
the collection of observed values, and let <span class="math inline">\(\mathbf{Z} = (\mathbf{Z}_{obs}, \mathbf{Z}_{mis})\)</span>.</p></li>
<li><p>The variables <span class="math inline">\(R_{ij}\)</span> are defined as
<span class="math display">\[\begin{equation}
R_{ij} =
\begin{cases}
1 &amp; \textrm{ if } Z_{ij} \textrm{ is missing } \\
0 &amp; \textrm{ if } Z_{ij} \textrm{ is observed }
\end{cases}
\end{equation}\]</span></p></li>
</ul>
<div id="missing-completely-at-random-mcar" class="section level3 hasAnchor" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Missing Completely at Random (MCAR)<a href="missing-data.html#missing-completely-at-random-mcar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>The <strong>missingness mechanism</strong> is said to be MCAR if
<span class="math display">\[\begin{equation}
P(R_{ij} = 1|\mathbf{Z}_{obs}, \mathbf{Z}_{mis}) = P(R_{ij}=1)
\end{equation}\]</span></li>
</ul>
</div>
<div id="missing-at-random-mar" class="section level3 hasAnchor" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Missing at Random (MAR)<a href="missing-data.html#missing-at-random-mar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>The <strong>missingness mechanism</strong> is said to be MAR if:
<span class="math display">\[\begin{equation}
P(R_{ij} = 1|\mathbf{Z}_{obs}, \mathbf{Z}_{mis}) = P(R_{ij}=1|\mathbf{Z}_{obs})
\end{equation}\]</span></p></li>
<li><p>If missingness is follows either MAR or MCAR, direct use of multiple imputation
is a valid approach.</p></li>
</ul>
</div>
<div id="missing-not-at-random-mnar" class="section level3 hasAnchor" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> Missing not at Random (MNAR)<a href="missing-data.html#missing-not-at-random-mnar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>If the <strong>missingness mechanism</strong> is classified as <strong>missing not at random</strong> (MNAR), the probability
<span class="math inline">\(P(R_{ij} = 1|\mathbf{Z}_{obs}, \mathbf{Z}_{mis})\)</span> cannot be factorized into a simpler form.</p></li>
<li><p>If the missingness is MNAR, direct use of multiple imputation may be invalid and
modeling of the missingness mechanism using subject-matter knowledge may be needed.</p></li>
<li><p>Use of multiple imputation with a sensitivity analysis is one approach to consider.</p></li>
</ul>
<hr />

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-buuren2010" class="csl-entry">
Buuren, S van, and Karin Groothuis-Oudshoorn. 2010. <span>“Mice: Multivariate Imputation by Chained Equations in r.”</span> <em>Journal of Statistical Software</em>, 1–68.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="mixed-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="nonpar-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
