<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Ordinal Regression | Notes for Case Studies in Health Big Data</title>
  <meta name="description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Ordinal Regression | Notes for Case Studies in Health Big Data" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  <meta name="github-repo" content="nchenderson/HDS629notes" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Ordinal Regression | Notes for Case Studies in Health Big Data" />
  
  <meta name="twitter:description" content="Course notes for Biostatistics 629: Case Studies in Health Big Data" />
  

<meta name="author" content="Nicholas Henderson" />


<meta name="date" content="2024-01-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="risk-prediction2.html"/>
<link rel="next" href="extra-topics.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Biostat 629</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="mixed-models.html"><a href="mixed-models.html"><i class="fa fa-check"></i><b>1</b> Mixed Models for Longitudinal Data Analysis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="mixed-models.html"><a href="mixed-models.html#sec:methods-overview"><i class="fa fa-check"></i><b>1.1</b> Methods for Analyzing Longitudinal Data</a></li>
<li class="chapter" data-level="1.2" data-path="mixed-models.html"><a href="mixed-models.html#mixed-models-for-continuous-outcomes"><i class="fa fa-check"></i><b>1.2</b> Mixed Models for Continuous Outcomes</a></li>
<li class="chapter" data-level="1.3" data-path="mixed-models.html"><a href="mixed-models.html#advantages-of-using-random-effects"><i class="fa fa-check"></i><b>1.3</b> Advantages of using random effects</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="mixed-models.html"><a href="mixed-models.html#within-subject-correlation"><i class="fa fa-check"></i><b>1.3.1</b> Within-subject correlation</a></li>
<li class="chapter" data-level="1.3.2" data-path="mixed-models.html"><a href="mixed-models.html#inference-about-heterogeneity---variance-of-random-effects"><i class="fa fa-check"></i><b>1.3.2</b> Inference about Heterogeneity - Variance of Random Effects</a></li>
<li class="chapter" data-level="1.3.3" data-path="mixed-models.html"><a href="mixed-models.html#best-linear-unbiased-prediction"><i class="fa fa-check"></i><b>1.3.3</b> Best Linear Unbiased Prediction</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="mixed-models.html"><a href="mixed-models.html#generalized-linear-mixed-models-glmms"><i class="fa fa-check"></i><b>1.4</b> Generalized linear mixed models (GLMMs)</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="mixed-models.html"><a href="mixed-models.html#glmms-with-binary-outcomes"><i class="fa fa-check"></i><b>1.4.1</b> GLMMs with Binary Outcomes</a></li>
<li class="chapter" data-level="1.4.2" data-path="mixed-models.html"><a href="mixed-models.html#glmms-with-count-outcomes"><i class="fa fa-check"></i><b>1.4.2</b> GLMMs with Count Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="mixed-models.html"><a href="mixed-models.html#fitting-linear-mixed-models-lmms-and-generalized-linear-mixed-models-glmms-in-r"><i class="fa fa-check"></i><b>1.5</b> Fitting Linear Mixed Models (LMMs) and Generalized Linear Mixed models (GLMMs) in <strong>R</strong></a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="mixed-models.html"><a href="mixed-models.html#fitting-lmms-with-the-sleepstudy-data"><i class="fa fa-check"></i><b>1.5.1</b> Fitting LMMs with the sleepstudy data</a></li>
<li class="chapter" data-level="1.5.2" data-path="mixed-models.html"><a href="mixed-models.html#model-comparison-of-lmms-using-anova"><i class="fa fa-check"></i><b>1.5.2</b> Model Comparison of LMMs using anova</a></li>
<li class="chapter" data-level="1.5.3" data-path="mixed-models.html"><a href="mixed-models.html#extracting-blups-in-lme4"><i class="fa fa-check"></i><b>1.5.3</b> Extracting BLUPs in lme4</a></li>
<li class="chapter" data-level="1.5.4" data-path="mixed-models.html"><a href="mixed-models.html#fitting-binary-glmms-using-the-ohio-data"><i class="fa fa-check"></i><b>1.5.4</b> Fitting Binary GLMMs using the Ohio data</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="mixed-models.html"><a href="mixed-models.html#exercises"><i class="fa fa-check"></i><b>1.6</b> Exercises</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="mixed-models.html"><a href="mixed-models.html#questions"><i class="fa fa-check"></i><b>1.6.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="missing-data.html"><a href="missing-data.html"><i class="fa fa-check"></i><b>2</b> Missing Data and Multiple Imputation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="missing-data.html"><a href="missing-data.html#missing-data-in-r-and-direct-approaches-for-handling-missing-data"><i class="fa fa-check"></i><b>2.1</b> Missing Data in R and “Direct Approaches” for Handling Missing Data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="missing-data.html"><a href="missing-data.html#complete-case-analysis-listwise-deletion"><i class="fa fa-check"></i><b>2.1.1</b> Complete Case Analysis (Listwise Deletion)</a></li>
<li class="chapter" data-level="2.1.2" data-path="missing-data.html"><a href="missing-data.html#other-direct-methods"><i class="fa fa-check"></i><b>2.1.2</b> Other “Direct” Methods</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="missing-data.html"><a href="missing-data.html#multiple-imputation"><i class="fa fa-check"></i><b>2.2</b> Multiple Imputation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="missing-data.html"><a href="missing-data.html#short-overview-of-multiple-imputation"><i class="fa fa-check"></i><b>2.2.1</b> Short Overview of Multiple Imputation</a></li>
<li class="chapter" data-level="2.2.2" data-path="missing-data.html"><a href="missing-data.html#multiple-imputation-with-mice"><i class="fa fa-check"></i><b>2.2.2</b> Multiple imputation with mice</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="missing-data.html"><a href="missing-data.html#what-is-mice-doing"><i class="fa fa-check"></i><b>2.3</b> What is MICE doing?</a></li>
<li class="chapter" data-level="2.4" data-path="missing-data.html"><a href="missing-data.html#longitudinal-data"><i class="fa fa-check"></i><b>2.4</b> Longitudinal Data</a></li>
<li class="chapter" data-level="2.5" data-path="missing-data.html"><a href="missing-data.html#different-missing-data-mechanisms"><i class="fa fa-check"></i><b>2.5</b> Different Missing Data Mechanisms</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="missing-data.html"><a href="missing-data.html#missing-completely-at-random-mcar"><i class="fa fa-check"></i><b>2.5.1</b> Missing Completely at Random (MCAR)</a></li>
<li class="chapter" data-level="2.5.2" data-path="missing-data.html"><a href="missing-data.html#missing-at-random-mar"><i class="fa fa-check"></i><b>2.5.2</b> Missing at Random (MAR)</a></li>
<li class="chapter" data-level="2.5.3" data-path="missing-data.html"><a href="missing-data.html#missing-not-at-random-mnar"><i class="fa fa-check"></i><b>2.5.3</b> Missing not at Random (MNAR)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="nonpar-regression.html"><a href="nonpar-regression.html"><i class="fa fa-check"></i><b>3</b> Nonparametric Regression with Longitudinal Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="nonpar-regression.html"><a href="nonpar-regression.html#notation"><i class="fa fa-check"></i><b>3.1</b> Notation</a></li>
<li class="chapter" data-level="3.2" data-path="nonpar-regression.html"><a href="nonpar-regression.html#kernel-smoothing"><i class="fa fa-check"></i><b>3.2</b> Kernel Smoothing</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="nonpar-regression.html"><a href="nonpar-regression.html#description-of-kernel-regression"><i class="fa fa-check"></i><b>3.2.1</b> Description of Kernel Regression</a></li>
<li class="chapter" data-level="3.2.2" data-path="nonpar-regression.html"><a href="nonpar-regression.html#kernel-regression-in-the-sleepstudy-data"><i class="fa fa-check"></i><b>3.2.2</b> Kernel Regression in the sleepstudy data</a></li>
<li class="chapter" data-level="3.2.3" data-path="nonpar-regression.html"><a href="nonpar-regression.html#bandwidth-selection"><i class="fa fa-check"></i><b>3.2.3</b> Bandwidth Selection</a></li>
<li class="chapter" data-level="3.2.4" data-path="nonpar-regression.html"><a href="nonpar-regression.html#another-example-the-bone-data"><i class="fa fa-check"></i><b>3.2.4</b> Another Example: The Bone Data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="nonpar-regression.html"><a href="nonpar-regression.html#regression-splines"><i class="fa fa-check"></i><b>3.3</b> Regression Splines</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="nonpar-regression.html"><a href="nonpar-regression.html#overview"><i class="fa fa-check"></i><b>3.3.1</b> Overview</a></li>
<li class="chapter" data-level="3.3.2" data-path="nonpar-regression.html"><a href="nonpar-regression.html#regression-splines-with-longitudinal-data-in-r"><i class="fa fa-check"></i><b>3.3.2</b> Regression Splines with Longitudinal Data in R</a></li>
<li class="chapter" data-level="3.3.3" data-path="nonpar-regression.html"><a href="nonpar-regression.html#looking-at-a-continuous-and-a-binary-covariate"><i class="fa fa-check"></i><b>3.3.3</b> Looking at a Continuous and a Binary Covariate</a></li>
<li class="chapter" data-level="3.3.4" data-path="nonpar-regression.html"><a href="nonpar-regression.html#model-comparison"><i class="fa fa-check"></i><b>3.3.4</b> Model Comparison</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="glmm-lasso.html"><a href="glmm-lasso.html"><i class="fa fa-check"></i><b>4</b> Sparse Regression for Longitudinal Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="glmm-lasso.html"><a href="glmm-lasso.html#sparse-regression-methods"><i class="fa fa-check"></i><b>4.1</b> Sparse regression methods</a></li>
<li class="chapter" data-level="4.2" data-path="glmm-lasso.html"><a href="glmm-lasso.html#the-lasso-with-longitudinal-data"><i class="fa fa-check"></i><b>4.2</b> The Lasso with longitudinal data</a></li>
<li class="chapter" data-level="4.3" data-path="glmm-lasso.html"><a href="glmm-lasso.html#lasso-for-lmms-and-glmms-in-r"><i class="fa fa-check"></i><b>4.3</b> Lasso for LMMs and GLMMs in R</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="glmm-lasso.html"><a href="glmm-lasso.html#soccer-data"><i class="fa fa-check"></i><b>4.3.1</b> Soccer Data</a></li>
<li class="chapter" data-level="4.3.2" data-path="glmm-lasso.html"><a href="glmm-lasso.html#choosing-the-tuning-parameter-for-the-soccer-data"><i class="fa fa-check"></i><b>4.3.2</b> Choosing the tuning parameter for the soccer data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="glmm-lasso.html"><a href="glmm-lasso.html#cross-validation-for-longitudinal-data"><i class="fa fa-check"></i><b>4.4</b> Cross-Validation for Longitudinal Data</a></li>
<li class="chapter" data-level="4.5" data-path="glmm-lasso.html"><a href="glmm-lasso.html#penalized-generalized-estimating-equations"><i class="fa fa-check"></i><b>4.5</b> Penalized Generalized Estimating Equations</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="glmm-lasso.html"><a href="glmm-lasso.html#the-pgee-package"><i class="fa fa-check"></i><b>4.5.1</b> The PGEE package</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="glmm-lasso.html"><a href="glmm-lasso.html#glmm-lasso-with-binary-outcomes"><i class="fa fa-check"></i><b>4.6</b> GLMM-Lasso with Binary Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="risk-prediction.html"><a href="risk-prediction.html"><i class="fa fa-check"></i><b>5</b> Risk Prediction and Validation (Part I)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="risk-prediction.html"><a href="risk-prediction.html#risk-predictionstratification"><i class="fa fa-check"></i><b>5.1</b> Risk Prediction/Stratification</a></li>
<li class="chapter" data-level="5.2" data-path="risk-prediction.html"><a href="risk-prediction.html#area-under-the-roc-curve-and-the-c-statistic"><i class="fa fa-check"></i><b>5.2</b> Area under the ROC curve and the C-statistic</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="risk-prediction.html"><a href="risk-prediction.html#sensitivity-and-specificity"><i class="fa fa-check"></i><b>5.2.1</b> Sensitivity and Specificity</a></li>
<li class="chapter" data-level="5.2.2" data-path="risk-prediction.html"><a href="risk-prediction.html#the-roc-curve"><i class="fa fa-check"></i><b>5.2.2</b> The ROC curve</a></li>
<li class="chapter" data-level="5.2.3" data-path="risk-prediction.html"><a href="risk-prediction.html#computing-the-roc-curve"><i class="fa fa-check"></i><b>5.2.3</b> Computing the ROC curve</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="risk-prediction.html"><a href="risk-prediction.html#area-under-the-roc-curve"><i class="fa fa-check"></i><b>5.3</b> Area under the ROC curve</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="risk-prediction.html"><a href="risk-prediction.html#rewriting-the-formula-for-the-auc"><i class="fa fa-check"></i><b>5.3.1</b> Rewriting the formula for the AUC</a></li>
<li class="chapter" data-level="5.3.2" data-path="risk-prediction.html"><a href="risk-prediction.html#interpreting-the-auc"><i class="fa fa-check"></i><b>5.3.2</b> Interpreting the AUC</a></li>
<li class="chapter" data-level="5.3.3" data-path="risk-prediction.html"><a href="risk-prediction.html#computing-the-auc-in-r"><i class="fa fa-check"></i><b>5.3.3</b> Computing the AUC in R</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="risk-prediction.html"><a href="risk-prediction.html#calibration"><i class="fa fa-check"></i><b>5.4</b> Calibration</a></li>
<li class="chapter" data-level="5.5" data-path="risk-prediction.html"><a href="risk-prediction.html#longitudinal-data-and-risk-score-validation"><i class="fa fa-check"></i><b>5.5</b> Longitudinal Data and Risk Score Validation</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="risk-prediction2.html"><a href="risk-prediction2.html"><i class="fa fa-check"></i><b>6</b> Risk Prediction and Validation (Part II)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="risk-prediction2.html"><a href="risk-prediction2.html#the-brier-score"><i class="fa fa-check"></i><b>6.1</b> The Brier Score</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="risk-prediction2.html"><a href="risk-prediction2.html#brier-scores-for-biopsy-data"><i class="fa fa-check"></i><b>6.1.1</b> Brier scores for biopsy data</a></li>
<li class="chapter" data-level="6.1.2" data-path="risk-prediction2.html"><a href="risk-prediction2.html#out-of-sample-comparisons"><i class="fa fa-check"></i><b>6.1.2</b> Out-of-sample comparisons</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="risk-prediction2.html"><a href="risk-prediction2.html#brier-scores-with-longitudinal-data"><i class="fa fa-check"></i><b>6.2</b> Brier Scores with Longitudinal Data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="risk-prediction2.html"><a href="risk-prediction2.html#option-1"><i class="fa fa-check"></i><b>6.2.1</b> Option 1</a></li>
<li class="chapter" data-level="6.2.2" data-path="risk-prediction2.html"><a href="risk-prediction2.html#option-2"><i class="fa fa-check"></i><b>6.2.2</b> Option 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ordinal-regression.html"><a href="ordinal-regression.html"><i class="fa fa-check"></i><b>7</b> Ordinal Regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ordinal-regression.html"><a href="ordinal-regression.html#ordinal-logistic-regression"><i class="fa fa-check"></i><b>7.1</b> Ordinal Logistic Regression</a></li>
<li class="chapter" data-level="7.2" data-path="ordinal-regression.html"><a href="ordinal-regression.html#ordinal-regression-details"><i class="fa fa-check"></i><b>7.2</b> Ordinal Regression Details</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ordinal-regression.html"><a href="ordinal-regression.html#ordinal-logistic-regression-in-r"><i class="fa fa-check"></i><b>7.2.1</b> Ordinal Logistic Regression in R</a></li>
<li class="chapter" data-level="7.2.2" data-path="ordinal-regression.html"><a href="ordinal-regression.html#the-respdis-data"><i class="fa fa-check"></i><b>7.2.2</b> The respdis data</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ordinal-regression.html"><a href="ordinal-regression.html#generalized-estimating-equations"><i class="fa fa-check"></i><b>7.3</b> Generalized Estimating Equations</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ordinal-regression.html"><a href="ordinal-regression.html#using-geepack-and-ordgee"><i class="fa fa-check"></i><b>7.3.1</b> Using geepack and ordgee</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ordinal-regression.html"><a href="ordinal-regression.html#penalized-regression-with-ordinal-outcomes"><i class="fa fa-check"></i><b>7.4</b> Penalized Regression with Ordinal Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="extra-topics.html"><a href="extra-topics.html"><i class="fa fa-check"></i><b>8</b> Extra Topics</a>
<ul>
<li class="chapter" data-level="8.1" data-path="extra-topics.html"><a href="extra-topics.html#uncertainty-in-variable-importance-measures"><i class="fa fa-check"></i><b>8.1</b> Uncertainty in Variable Importance Measures</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="extra-topics.html"><a href="extra-topics.html#subsampling-for-random-forest-vimp-scores"><i class="fa fa-check"></i><b>8.1.1</b> Subsampling for Random Forest VIMP scores</a></li>
<li class="chapter" data-level="8.1.2" data-path="extra-topics.html"><a href="extra-topics.html#stability-selection-for-penalized-regression"><i class="fa fa-check"></i><b>8.1.2</b> Stability Selection for Penalized Regression</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notes for Case Studies in Health Big Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ordinal-regression" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Ordinal Regression<a href="ordinal-regression.html#ordinal-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<hr />
<div id="ordinal-logistic-regression" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Ordinal Logistic Regression<a href="ordinal-regression.html#ordinal-logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>In many applications, the possible values of the response should be
thought of as <strong>ordered categories</strong>.</p></li>
<li><p><strong>Examples:</strong></p>
<ul>
<li><p>Survey ratings of a product: “poor”, “good”, “excellent”.</p></li>
<li><p>Patient reported scale of pain from 1-10.</p></li>
<li><p>Different possible responses on a questionnaire.</p></li>
</ul></li>
</ul>
</div>
<div id="ordinal-regression-details" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Ordinal Regression Details<a href="ordinal-regression.html#ordinal-regression-details" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>With <strong>ordinal regression</strong>, only the <strong>ranking</strong> of the different
categories is relevant.</li>
</ul>
<hr />
<ul>
<li><p>Let <span class="math inline">\(Y_{i}\)</span> represent the <strong>ordinal response</strong> of interest.</p></li>
<li><p>Assume <span class="math inline">\(Y_{i}\)</span> can take an integer value from 1 to C: <span class="math inline">\(Y_{i} = 1\)</span>,
or <span class="math inline">\(Y_{i} = 2\)</span>, …, or <span class="math inline">\(Y_{i} = C\)</span>.</p>
<ul>
<li>Although we are assuming <span class="math inline">\(Y_{i}\)</span> takes numerical values, the
ordinal regression analysis would be the same if we assumed that
<span class="math inline">\(Y_{i}\)</span> could take values <span class="math inline">\(2, 4, 6, ..., 2C\)</span>.</li>
</ul></li>
</ul>
<hr />
<ul>
<li><p>The most common regression model for ordinal data is an <strong>ordinal logistic regression model</strong>.</p></li>
<li><p>The ordinal logistic regression model uses a regression model for
the <strong>“lesser-than probabilities”</strong> <span class="math inline">\(P( Y_{i} \leq c|\mathbf{x}_{i})\)</span>.</p></li>
<li><p>Specifically, <span class="math display">\[\begin{equation}
P(Y_{i} \leq c|\mathbf{x}_{i}) = \frac{1}{1 + \exp(-\alpha_{c} + \mathbf{x}_{i}^{T}\boldsymbol{\beta})}, \quad c = 1, \ldots, C-1
\end{equation}\]</span></p></li>
<li><p>This is equivalent to saying that the <strong>log-odds</strong> (for the
event <span class="math inline">\(\{Y_{i} \leq c\}\)</span>) is a <strong>linear function</strong> of the covariates:
<span class="math display" id="eq:ologist-model">\[\begin{equation}
\log \{ \text{odds}_{c}( \mathbf{x}_{i} ) \} = \log\left( \frac{ P(Y_{i} \leq c|\mathbf{x}_{i}) }{ 1 - P(Y_{i} \leq c|\mathbf{x}_{i}) }  \right) = \alpha_{c} - \mathbf{x}_{i}^{T}\boldsymbol{\beta}
\tag{7.1}
\end{equation}\]</span></p></li>
</ul>
<hr />
<ul>
<li>Note that the ordinal logistic regression model is often expressed
using the probabilities <span class="math inline">\(P(Y_{i} &gt; c|\mathbf{x}_{i})\)</span> instead of
<span class="math inline">\(P( Y_{i} &gt; c|\mathbf{x}_{i})\)</span> where it is assumed that
<span class="math display">\[\begin{equation}
\log\left( \frac{ P(Y_{i} &gt; c|\mathbf{x}_{i}) }{ 1 - P(Y_{i} &gt; c|\mathbf{x}_{i}) }  \right) = \alpha_{c} + \mathbf{x}_{i}^{T}\boldsymbol{\beta}
\end{equation}\]</span></li>
</ul>
<hr />
<ul>
<li><p>The regression model <a href="ordinal-regression.html#eq:ologist-model">(7.1)</a> is often called a
<strong>proportional odds</strong> model.</p>
<ul>
<li>This is because the odds ratio for the probability
<span class="math inline">\(P(Y \leq c|\mathbf{x}_{i})\)</span> vs. the probability
<span class="math inline">\(P(Y \leq c|\mathbf{z}_{i})\)</span> does not depend on the value of
<span class="math inline">\(c\)</span>.</li>
</ul></li>
<li><p>To see the <strong>proportional odds property</strong>, note that
<span class="math display">\[\begin{equation}
\frac{ \text{odds}_{c}( \mathbf{x}_{i} ) }{ \text{odds}_{c}( \mathbf{z}_{i} ) }
= \frac{ \exp( \alpha_{c} - \mathbf{x}_{i}^{T}\boldsymbol{\beta} ) }{ \exp( \alpha_{c} - \mathbf{z}_{i}^{T}\boldsymbol{\beta} ) }
= \exp\left[ (\mathbf{z}_{i}^{T} - \mathbf{x}_{i}^{T})\boldsymbol{\beta} \right]
\end{equation}\]</span></p></li>
<li><p>The odds ratio <strong>only depends</strong> on <span class="math inline">\(\boldsymbol{\beta}\)</span> and <strong>does not depend</strong> on the value of <span class="math inline">\(\alpha_{c}\)</span>.</p></li>
</ul>
<hr />
<ul>
<li><p>The proportional odds assumption allows the elements of
<span class="math inline">\(\boldsymbol{\beta}\)</span> to have an interpretation that <strong>does not</strong>
depend on <span class="math inline">\(c\)</span>.</p></li>
<li><p><strong>Interpretation</strong>: If you have only one covariate <span class="math inline">\(x_{i}\)</span>, then a
one-unit increase in <span class="math inline">\(x_{i}\)</span> leads to an increase of <span class="math inline">\(\beta\)</span> in the
<strong>log-odds ratio</strong> (for the event <span class="math inline">\(\{Y_{i}\leq c\}\)</span>): <span class="math display">\[\begin{equation}
\log\left( \frac{ \text{odds}_{c}( x_{i} + 1 ) }{ \text{odds}_{c}( x_{i} ) } \right)
=  -\beta
\end{equation}\]</span></p></li>
</ul>
<hr />
<ul>
<li>The model <a href="ordinal-regression.html#eq:ologist-model">(7.1)</a> uses a <strong>logit</strong> link function,
but it’s possible to choose any other link function.
<ul>
<li>Common alternative choices are the <strong>complementary log-log</strong> and
<strong>probit</strong> link functions.</li>
</ul></li>
</ul>
<div id="ordinal-logistic-regression-in-r" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Ordinal Logistic Regression in R<a href="ordinal-regression.html#ordinal-logistic-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>The <strong>polr</strong> function in the <strong>MASS</strong> package let’s you fit
<strong>ordered logistic</strong> or <strong>ordered probit</strong> regression models.</p></li>
<li><p>The example dataset in the <strong>polr</strong> documentation is the <code>housing</code>
data</p></li>
</ul>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="ordinal-regression.html#cb280-1" tabindex="-1"></a><span class="fu">library</span>(MASS)  <span class="co"># load MASS package</span></span>
<span id="cb280-2"><a href="ordinal-regression.html#cb280-2" tabindex="-1"></a><span class="fu">head</span>(housing)  <span class="co"># look at first 6 rows</span></span></code></pre></div>
<pre><code>##      Sat   Infl  Type Cont Freq
## 1    Low    Low Tower  Low   21
## 2 Medium    Low Tower  Low   21
## 3   High    Low Tower  Low   28
## 4    Low Medium Tower  Low   34
## 5 Medium Medium Tower  Low   22
## 6   High Medium Tower  Low   36</code></pre>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="ordinal-regression.html#cb282-1" tabindex="-1"></a><span class="fu">dim</span>(housing)  <span class="co"># 72 rows and 5 variables</span></span></code></pre></div>
<pre><code>## [1] 72  5</code></pre>
<hr />
<ul>
<li><p>The syntax for using <code>polr</code> is similar to other common regression-fitting functions in <strong>R</strong> such as <code>lm</code> or <code>glm</code>.</p></li>
<li><p>The main thing to be aware of when using <code>polr</code> is that the response
variable should be an <strong>ordered factor</strong>.</p></li>
</ul>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="ordinal-regression.html#cb284-1" tabindex="-1"></a><span class="fu">str</span>(housing)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    72 obs. of  5 variables:
##  $ Sat : Ord.factor w/ 3 levels &quot;Low&quot;&lt;&quot;Medium&quot;&lt;..: 1 2 3 1 2 3 1 2 3 1 ...
##  $ Infl: Factor w/ 3 levels &quot;Low&quot;,&quot;Medium&quot;,..: 1 1 1 2 2 2 3 3 3 1 ...
##  $ Type: Factor w/ 4 levels &quot;Tower&quot;,&quot;Apartment&quot;,..: 1 1 1 1 1 1 1 1 1 2 ...
##  $ Cont: Factor w/ 2 levels &quot;Low&quot;,&quot;High&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Freq: int  21 21 28 34 22 36 10 11 36 61 ...</code></pre>
<ul>
<li><p>The <strong>response variable</strong> of interest here is <code>Sat</code> which represents
householder satisfaction.</p>
<ul>
<li><p>This has 3 possible responses: <strong>“Low”</strong>, <strong>“Medium”</strong>, or
<strong>“High”</strong>.</p></li>
<li><p>This is a categorical variable with a natural ordering (“Low” is worse than “Medium” which is worse than “High”).</p></li>
</ul>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="ordinal-regression.html#cb286-1" tabindex="-1"></a><span class="fu">table</span>(housing<span class="sc">$</span>Sat)</span></code></pre></div>
<pre><code>## 
##    Low Medium   High 
##     24     24     24</code></pre></li>
</ul>
<hr />
<ul>
<li><p>The categorial variables <code>Sat</code>, <code>Infl</code>, <code>Type</code>, and <code>Cont</code> don’t
have the <strong>“individual-level”</strong> data.</p>
<ul>
<li>Each row just represents one of the 72 possible configurations
of these variables.</li>
</ul></li>
<li><p>The variable <code>Freq</code> actually tells us <strong>how many responses</strong> we had for
each of the 72 categories.</p></li>
<li><p>To fit this without using the individual-level data, we can use the
values of <code>Freq</code> as <strong>weights</strong> in an ordinal logistic regression.</p></li>
</ul>
<hr />
<ul>
<li>If we want to fit an ordinal logistic regression with <code>Sat</code> as the
<strong>response</strong> and <code>Infl</code> as a <strong>covariate</strong>, we can use the following code:</li>
</ul>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="ordinal-regression.html#cb288-1" tabindex="-1"></a>infl.plr <span class="ot">&lt;-</span> <span class="fu">polr</span>(Sat <span class="sc">~</span> Infl, <span class="at">weight=</span>Freq, <span class="at">data =</span> housing)</span></code></pre></div>
<ul>
<li>The above <strong>R code</strong> is going to fit the model <span class="math display">\[\begin{equation}
\log \left( \frac{ P(Y_{i} \leq c|\mathbf{x}_{i}) }{1 - P(Y_{i} \leq c|\mathbf{x}_{i})} \right) = \alpha_{c} - \beta_{1}x_{i1} - \beta_{2}x_{i2},
\end{equation}\]</span>
<ul>
<li><span class="math inline">\(Y_{i}\)</span> is the satisfaction level with three levels</li>
<li><span class="math inline">\(x_{i1} = 1\)</span> if influence is medium and <span class="math inline">\(0\)</span> otherwise</li>
<li><span class="math inline">\(x_{i2} = 1\)</span> if influence is high and <span class="math inline">\(0\)</span> otherwise.</li>
</ul></li>
</ul>
<hr />
<ul>
<li>To see the <strong>estimates</strong> of these parameters use the <code>summary</code>
function:</li>
</ul>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="ordinal-regression.html#cb289-1" tabindex="-1"></a><span class="fu">summary</span>(infl.plr)</span></code></pre></div>
<pre><code>## 
## Re-fitting to get Hessian</code></pre>
<pre><code>## Call:
## polr(formula = Sat ~ Infl, data = housing, weights = Freq)
## 
## Coefficients:
##             Value Std. Error t value
## InflMedium 0.5636     0.1036   5.441
## InflHigh   1.2487     0.1248  10.006
## 
## Intercepts:
##             Value   Std. Error t value
## Low|Medium  -0.2014  0.0766    -2.6280
## Medium|High  0.9485  0.0802    11.8199
## 
## Residual Deviance: 3543.416 
## AIC: 3551.416</code></pre>
<ul>
<li><p>The above coefficient estimates tell us that the odds of <strong>low satisfaction</strong> given <strong>Medium</strong> influence level vs. the odds of
<strong>low satisfaction</strong> given a <strong>Low</strong> influence level is
<span class="math display">\[\begin{equation}
\frac{odds_{c}(\text{Medium Influence})}{odds_{c}(\text{Low Influence})} = \exp(-\hat{\beta}_{1}) = \exp(-0.563) \approx 0.57
\end{equation}\]</span></p>
<ul>
<li>In other words, the odds of having <strong>low satisfaction</strong> are
higher in the low influence group when compared to the high
influence group.</li>
</ul></li>
<li><p>Similarly, the <strong>odds ratio</strong> for the high influence group vs. the
low influence group is given by <span class="math display">\[\begin{equation}
\frac{\text{odds}_{c}(\text{High Influence})}{\text{odds}_{c}(\text{Low Influence})} = \exp(-\hat{\beta}_{2}) = \exp(-1.248) \approx 0.29
\end{equation}\]</span></p></li>
<li><p>From this, you can get the <strong>odds ratio</strong> for high vs. medium
influence levels <span class="math display">\[\begin{equation}
\frac{\text{odds}_{c}(\text{High Influence})}{\text{odds}_{c}(\text{Medium Influence})} = \exp(-1.248) \exp(0.563) \approx 0.5
\end{equation}\]</span></p></li>
</ul>
<hr />
<ul>
<li><p>The summary output from a <code>polr</code> fit will also give estimates of the
<strong>“intercept terms”</strong> <span class="math inline">\(\alpha_{c}\)</span>.</p></li>
<li><p>Since there are only <strong>3 possible levels</strong> of the response <code>Sat</code>, there
should only be two possible values of <span class="math inline">\(\alpha_{c}\)</span>.</p></li>
<li><p>The estimates <span class="math inline">\(\hat{\alpha}_{c}\)</span> are given in the <code>Intercepts</code> part
of the summary output.</p></li>
<li><p>The estimate of <span class="math inline">\(\hat{\alpha}_{1}\)</span> means that the probability that
satisfaction is low (i.e., <span class="math inline">\(Y_{i} \leq 1\)</span>) given low influence is
<span class="math display">\[\begin{equation}
\hat{P}(Y_{i} \leq 1| \text{InflLow}) = 1/[1 + \exp(-\hat{\alpha}_{1})] \approx 0.45
\end{equation}\]</span></p></li>
<li><p>Similarly, the estimated probability that satisfaction is low given
medium influence is <span class="math display">\[\begin{equation}
\hat{P}(Y_{i} \leq 1| \text{InflMed}) = 1/[1 + \exp(-\hat{\alpha}_{1} + \hat{\beta}_{1})] \approx 0.31
\end{equation}\]</span></p></li>
</ul>
<hr />
<ul>
<li><p>In this case, because we are only looking at a single covariate, we
can verify these probability estimates with a direct calculation.</p></li>
<li><p>The estimate of <span class="math inline">\(P(Y_{i} \leq 1| \text{InflLow})\)</span> should be equal to
the following ratio <span class="math display">\[\begin{equation}
\hat{P}(Y_{i} \leq 1| \text{InflLow}) = \frac{ N_{satlow, infllow} }{ N_{infllow} }
\end{equation}\]</span></p></li>
<li><p>This can be computed with the <strong>R</strong> code</p></li>
</ul>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="ordinal-regression.html#cb292-1" tabindex="-1"></a>N_ll <span class="ot">&lt;-</span> <span class="fu">sum</span>(housing<span class="sc">$</span>Freq[housing<span class="sc">$</span>Sat<span class="sc">==</span><span class="st">&quot;Low&quot;</span> <span class="sc">&amp;</span> housing<span class="sc">$</span>Infl<span class="sc">==</span><span class="st">&quot;Low&quot;</span>])</span>
<span id="cb292-2"><a href="ordinal-regression.html#cb292-2" tabindex="-1"></a>N_l <span class="ot">&lt;-</span> <span class="fu">sum</span>(housing<span class="sc">$</span>Freq[housing<span class="sc">$</span>Infl<span class="sc">==</span><span class="st">&quot;Low&quot;</span>])</span>
<span id="cb292-3"><a href="ordinal-regression.html#cb292-3" tabindex="-1"></a>N_ll<span class="sc">/</span>N_l</span></code></pre></div>
<pre><code>## [1] 0.4497608</code></pre>
<ul>
<li>A direct estimate of <span class="math inline">\(\hat{P}(Y_{i} \leq 1| \text{InflMed})\)</span> can be
computed with the following <strong>R</strong> code</li>
</ul>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="ordinal-regression.html#cb294-1" tabindex="-1"></a>N_lm <span class="ot">&lt;-</span> <span class="fu">sum</span>(housing<span class="sc">$</span>Freq[housing<span class="sc">$</span>Sat<span class="sc">==</span><span class="st">&quot;Low&quot;</span> <span class="sc">&amp;</span> housing<span class="sc">$</span>Infl<span class="sc">==</span><span class="st">&quot;Medium&quot;</span>])</span>
<span id="cb294-2"><a href="ordinal-regression.html#cb294-2" tabindex="-1"></a>N_m <span class="ot">&lt;-</span> <span class="fu">sum</span>(housing<span class="sc">$</span>Freq[housing<span class="sc">$</span>Infl<span class="sc">==</span><span class="st">&quot;Medium&quot;</span>])</span>
<span id="cb294-3"><a href="ordinal-regression.html#cb294-3" tabindex="-1"></a>N_lm<span class="sc">/</span>N_m</span></code></pre></div>
<pre><code>## [1] 0.3125948</code></pre>
</div>
<div id="the-respdis-data" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> The respdis data<a href="ordinal-regression.html#the-respdis-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>As another example, let’s look at the <code>respdis</code> data from the
<code>geepack</code> package</li>
</ul>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="ordinal-regression.html#cb296-1" tabindex="-1"></a><span class="fu">library</span>(geepack)</span>
<span id="cb296-2"><a href="ordinal-regression.html#cb296-2" tabindex="-1"></a><span class="fu">head</span>(respdis)</span></code></pre></div>
<pre><code>##   y1 y2 y3 y4 trt
## 1  1  1  1  1   1
## 2  1  1  1  1   0
## 3  1  1  1  1   0
## 4  1  1  1  1   0
## 5  1  1  1  1   0
## 6  1  1  1  1   0</code></pre>
<ul>
<li>This is a <strong>longitudinal dataset</strong>. For this analysis,
we will only look at the outcome at the <strong>first visit</strong></li>
</ul>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="ordinal-regression.html#cb298-1" tabindex="-1"></a>respdis_first <span class="ot">&lt;-</span> respdis[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>)]</span>
<span id="cb298-2"><a href="ordinal-regression.html#cb298-2" tabindex="-1"></a><span class="fu">head</span>(respdis_first)</span></code></pre></div>
<pre><code>##   y1 trt
## 1  1   1
## 2  1   0
## 3  1   0
## 4  1   0
## 5  1   0
## 6  1   0</code></pre>
<ul>
<li><p>The <code>y1</code> variable represents an <strong>ordinal outcome</strong> (poor, good, or excellent) at the first visit</p></li>
<li><p>The outcomes are coded as 1,2,3 in the <code>respdis_first</code> dataset</p></li>
</ul>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="ordinal-regression.html#cb300-1" tabindex="-1"></a><span class="fu">table</span>(respdis<span class="sc">$</span>y1)</span></code></pre></div>
<pre><code>## 
##  1  2  3 
## 14 63 34</code></pre>
<hr />
<ul>
<li>Let’s fit an <strong>ordered regression model</strong> using <code>trt</code> as the only covariate.
<ul>
<li>We need to put <code>ordered(y1)</code> in the model formula since y1 is not stored as a <strong>factor</strong> in <code>respdis_first</code></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="ordinal-regression.html#cb302-1" tabindex="-1"></a>respmod_first <span class="ot">&lt;-</span> <span class="fu">polr</span>(<span class="fu">ordered</span>(y1) <span class="sc">~</span> trt, <span class="at">data=</span>respdis_first)</span></code></pre></div>
<ul>
<li>The above <strong>R code</strong> is going to fit the model
<span class="math display">\[\begin{equation}
\log \left( \frac{ P(Y_{i} \leq c|\mathbf{x}_{i}) }{1 - P(Y_{i} \leq c|\mathbf{x}_{i})} \right) = \alpha_{c} - \beta x_{i},
\end{equation}\]</span></li>
<li><span class="math inline">\(Y_{i}\)</span> is the response level with three levels</li>
<li><span class="math inline">\(x_{i} = 1\)</span> if received treatment, <span class="math inline">\(x_{i} = 0\)</span> if received placebo</li>
</ul>
<hr />
<ul>
<li>Let’s look at the <strong>summary output</strong> from <code>respmod_first</code>:</li>
</ul>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="ordinal-regression.html#cb303-1" tabindex="-1"></a><span class="fu">summary</span>(respmod_first)</span></code></pre></div>
<pre><code>## 
## Re-fitting to get Hessian</code></pre>
<pre><code>## Call:
## polr(formula = ordered(y1) ~ trt, data = respdis_first)
## 
## Coefficients:
##      Value Std. Error t value
## trt 0.4467     0.3743   1.194
## 
## Intercepts:
##     Value   Std. Error t value
## 1|2 -1.7302  0.3300    -5.2429
## 2|3  1.0512  0.2885     3.6439
## 
## Residual Deviance: 208.3581 
## AIC: 214.3581</code></pre>
<ul>
<li><p>The estimate of <span class="math inline">\(\hat{\beta}\)</span> implies that:
<span class="math display">\[\begin{equation}
\frac{\text{odds}_{c}(\text{Treatment})}{\text{odds}_{c}(\text{Placebo})} = \exp(-\hat{\beta}) = \exp(-0.447) \approx 0.64
\end{equation}\]</span></p></li>
<li><p>In this context, having a low odds of <span class="math inline">\(Y_{i} \leq c\)</span> (for c=1,2) is good.</p></li>
<li><p>Hence, the above odds ratio <strong>suggests a benefit</strong> of treatment vs. placebo.</p></li>
</ul>
<hr />
<ul>
<li>Using the <strong>estimates</strong> of <span class="math inline">\(\alpha_{1}\)</span> and <span class="math inline">\(\alpha_{2}\)</span>,
you can get estimates of <span class="math inline">\(Y_{i} \leq c\)</span> for the <strong>treatment and placebo</strong> groups:
<span class="math display">\[\begin{eqnarray}
\hat{P}( Y_{i} \leq 1| \text{treatment} ) &amp;=&amp; \frac{1}{ 1 + \exp(-\hat{\alpha}_{1} + \hat{\beta})} = \frac{1}{ 1 + \exp(1.73 + 0.45 )} \approx 0.10 \nonumber \\
\hat{P}( Y_{i} \leq 1| \text{placebo} ) &amp;=&amp; \frac{1}{ 1 + \exp(-\hat{\alpha}_{1})} = \frac{1}{ 1 + \exp(1.73)} \approx 0.15
\end{eqnarray}\]</span></li>
</ul>
</div>
</div>
<div id="generalized-estimating-equations" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Generalized Estimating Equations<a href="ordinal-regression.html#generalized-estimating-equations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>With <strong>longitudinal data</strong>, you can fit <strong>random effects</strong> ordinal
regression models with the <code>repolr</code> package.</p></li>
<li><p>A <strong>GEE approach for ordinal outcomes</strong> can be done with the <code>ordgee</code>
function from the <code>geepack</code> package.</p></li>
</ul>
<hr />
<ul>
<li><p>For longitudinal data, let <span class="math inline">\(Y_{ij}\)</span> be the ordinal response for
individual <span class="math inline">\(i\)</span> at time <span class="math inline">\(t_{ij}\)</span>.</p></li>
<li><p>The GEE approach described in (<span class="citation">Heagerty and Zeger (<a href="#ref-heagerty1996">1996</a>)</span>) assumes the <strong>“mean part”</strong> of the model has the form
<span class="math display">\[\begin{equation}
P(Y_{ij} &gt; c|\mathbf{x}_{i}) = \frac{1}{1 + \exp(-\alpha_{c} - \mathbf{x}_{i}^{T}\boldsymbol{\beta})}
\end{equation}\]</span></p></li>
<li><p>The above equation handles the <strong>marginal distribution</strong> of <span class="math inline">\(Y_{ij}\)</span>
at a specific time point.</p></li>
<li><p>For a GEE, the only remaining part is how to handle the
<strong>“correlation” structure</strong> between observations from individual
<span class="math inline">\(i\)</span>.</p></li>
</ul>
<hr />
<ul>
<li><p>Setting up a <strong>“correlation” structure</strong> for ordinal outcomes is not
that straightforward. The approach described below is that described
in ( <span class="citation">Heagerty and Zeger (<a href="#ref-heagerty1996">1996</a>)</span> ).</p>
<ul>
<li><p>You don’t want to work with the usual definition of correlation
because we are not treating these outcomes as <strong>numeric
outcomes</strong>.</p></li>
<li><p>Instead the <strong>dependence</strong> is expressed through different
<strong>joint probabilities</strong>.</p></li>
</ul></li>
<li><p>The dependence between ordinal outcomes <span class="math inline">\(Y_{ij}\)</span> and <span class="math inline">\(Y_{ik}\)</span> is
measured by the <strong>“marginal odds ratios”</strong> <span class="math display">\[\begin{equation}
\psi_{i(j,k)(c_{1},c_{2})} = \frac{P(Y_{ij} &gt; c_{1}, Y_{ik} &gt; c_{2}|\mathbf{x}_{ij},\mathbf{x}_{ij}) P(Y_{ij} \leq c_{1}, Y_{ik} \leq c_{2}|\mathbf{x}_{ij},\mathbf{x}_{ij})}{P(Y_{ij} &gt; c_{1}, Y_{ik} \leq c_{2}|\mathbf{x}_{ij},\mathbf{x}_{ij}) P(Y_{ij} \leq c_{1}, Y_{ik} &gt; c_{2}|\mathbf{x}_{ij},\mathbf{x}_{ij})}
\end{equation}\]</span></p></li>
<li><p>If <span class="math inline">\(Y_{ij}\)</span> and <span class="math inline">\(Y_{ik}\)</span> have high dependence, then
<span class="math inline">\(\psi_{i(j,k)(c_{1},c_{2})}\)</span> should be large.</p></li>
</ul>
<hr />
<ul>
<li><p>The “<strong>exchangeable</strong>” correlation structure assumes that the
odds-ratio parameter is constant <span class="math display">\[\begin{equation}
\log\left( \psi_{i(j,k)(c_{1},c_{2})} \right) = \alpha
\end{equation}\]</span> for all <span class="math inline">\((j,k)\)</span> and <span class="math inline">\((c_{1}, c_{2})\)</span>.</p></li>
<li><p>The “<strong>independent</strong>” correlation structure assumes that
<span class="math inline">\(\alpha = 0\)</span> since <span class="math inline">\(\psi_{i(j,k)(c_{1},c_{2})} = 1\)</span> if we assume
that <span class="math inline">\(Y_{ij}\)</span> and <span class="math inline">\(Y_{ik}\)</span> are independent.</p></li>
</ul>
<div id="using-geepack-and-ordgee" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Using geepack and ordgee<a href="ordinal-regression.html#using-geepack-and-ordgee" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>The <code>ordgee</code> function from the <code>geepack</code> package allows you to fit a
GEE with <strong>ordinal responses</strong>.</p></li>
<li><p>To show how to use <code>ordgee</code>, we can look at the <code>respdis</code> dataset
from the <code>geepack</code> package</p></li>
</ul>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="ordinal-regression.html#cb306-1" tabindex="-1"></a><span class="fu">library</span>(geepack)</span>
<span id="cb306-2"><a href="ordinal-regression.html#cb306-2" tabindex="-1"></a><span class="fu">data</span>(respdis)</span>
<span id="cb306-3"><a href="ordinal-regression.html#cb306-3" tabindex="-1"></a>resp.l <span class="ot">&lt;-</span> <span class="fu">reshape</span>(respdis, <span class="at">varying =</span><span class="fu">list</span>(<span class="fu">c</span>(<span class="st">&quot;y1&quot;</span>, <span class="st">&quot;y2&quot;</span>, <span class="st">&quot;y3&quot;</span>, <span class="st">&quot;y4&quot;</span>)),</span>
<span id="cb306-4"><a href="ordinal-regression.html#cb306-4" tabindex="-1"></a>                  <span class="at">v.names =</span> <span class="st">&quot;resp&quot;</span>, <span class="at">direction =</span> <span class="st">&quot;long&quot;</span>)</span>
<span id="cb306-5"><a href="ordinal-regression.html#cb306-5" tabindex="-1"></a>resp.l <span class="ot">&lt;-</span> resp.l[<span class="fu">order</span>(resp.l<span class="sc">$</span>id, resp.l<span class="sc">$</span>time),]</span>
<span id="cb306-6"><a href="ordinal-regression.html#cb306-6" tabindex="-1"></a><span class="fu">head</span>(resp.l)</span></code></pre></div>
<pre><code>##     trt time resp id
## 1.1   1    1    1  1
## 1.2   1    2    1  1
## 1.3   1    3    1  1
## 1.4   1    4    1  1
## 2.1   0    1    1  2
## 2.2   0    2    1  2</code></pre>
<ul>
<li>The response of interest here is the variable <code>resp</code> which has 3
possible values:</li>
</ul>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="ordinal-regression.html#cb308-1" tabindex="-1"></a><span class="fu">table</span>(resp.l<span class="sc">$</span>resp)</span></code></pre></div>
<pre><code>## 
##   1   2   3 
##  80 212 152</code></pre>
<hr />
<ul>
<li>The syntax for <code>ordgee</code> is basically the same as <code>geeglm</code>.
<ul>
<li><p>Just make sure the response is an <strong>ordered factor</strong>.</p></li>
<li><p>The main available correlation structures are <strong>“independence”</strong>
and <strong>“exchangeable”</strong>.</p></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="ordinal-regression.html#cb310-1" tabindex="-1"></a><span class="do">## Fit GEE with just trt as a covariate</span></span>
<span id="cb310-2"><a href="ordinal-regression.html#cb310-2" tabindex="-1"></a>fit.indep <span class="ot">&lt;-</span> <span class="fu">ordgee</span>(<span class="fu">ordered</span>(resp) <span class="sc">~</span> trt, <span class="at">id=</span>id, <span class="at">corstr=</span><span class="st">&quot;independence&quot;</span>,</span>
<span id="cb310-3"><a href="ordinal-regression.html#cb310-3" tabindex="-1"></a>                    <span class="at">data=</span>resp.l)</span>
<span id="cb310-4"><a href="ordinal-regression.html#cb310-4" tabindex="-1"></a><span class="fu">summary</span>(fit.indep)</span></code></pre></div>
<pre><code>## 
## Call:
## ordgee(formula = ordered(resp) ~ trt, id = id, data = resp.l, 
##     corstr = &quot;independence&quot;)
## 
## Mean Model:
##  Mean Link:                 logit 
##  Variance to Mean Relation: binomial 
## 
##  Coefficients:
##          estimate    san.se      wald            p
## Inter:1  1.139907 0.2365456 23.222502 1.442990e-06
## Inter:2 -1.139907 0.2417271 22.237619 2.409072e-06
## trt      0.976700 0.3161920  9.541586 2.008680e-03
## 
## Scale is fixed.
## 
## Correlation Model:
##  Correlation Structure:     independence 
## 
## Returned Error Value:    0 
## Number of clusters:   111   Maximum cluster size: 4</code></pre>
<ul>
<li><p>The terms <code>Inter:1</code>, <code>Inter:2</code> in the summary output represent the
estimates of the intercept parameters <span class="math inline">\(\alpha_{1}\)</span> and <span class="math inline">\(\alpha_{2}\)</span>.</p></li>
<li><p>The estimate of the <code>trt</code> regression coefficient implies that the
odds ratio (between <code>trt = 1</code> and <code>trt = 0</code>) for having a positive
outcome is roughly <span class="math inline">\(2.6\)</span> <span class="math display">\[\begin{equation}
\frac{\text{odds}_{Y_{i} &gt; c}(trt=1) }{\text{odds}_{Y_{i} &gt; c}(trt=0) } = \exp(0.97) \approx 2.65
\end{equation}\]</span></p></li>
</ul>
<hr />
<ul>
<li>To fit the same model with an <strong>exchangeable</strong> correlation
structure, just use the <code>corstr = exchangeable</code> argument:</li>
</ul>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="ordinal-regression.html#cb312-1" tabindex="-1"></a><span class="do">## Fit GEE with just trt as a covariate</span></span>
<span id="cb312-2"><a href="ordinal-regression.html#cb312-2" tabindex="-1"></a>fit.ex <span class="ot">&lt;-</span> <span class="fu">ordgee</span>(<span class="fu">ordered</span>(resp) <span class="sc">~</span> trt, <span class="at">id=</span>id, <span class="at">corstr=</span><span class="st">&quot;exchangeable&quot;</span>,</span>
<span id="cb312-3"><a href="ordinal-regression.html#cb312-3" tabindex="-1"></a>                    <span class="at">data=</span>resp.l)</span>
<span id="cb312-4"><a href="ordinal-regression.html#cb312-4" tabindex="-1"></a><span class="fu">summary</span>(fit.ex)</span></code></pre></div>
<pre><code>## 
## Call:
## ordgee(formula = ordered(resp) ~ trt, id = id, data = resp.l, 
##     corstr = &quot;exchangeable&quot;)
## 
## Mean Model:
##  Mean Link:                 logit 
##  Variance to Mean Relation: binomial 
## 
##  Coefficients:
##          estimate    san.se      wald            p
## Inter:1  1.140030 0.2369495 23.148392 1.499686e-06
## Inter:2 -1.140030 0.2421280 22.168817 2.496965e-06
## trt      1.012671 0.3357436  9.097488 2.559608e-03
## 
## Scale is fixed.
## 
## Correlation Model:
##  Correlation Structure:     exchangeable 
##  Correlation Link:          log 
## 
##  Estimated Correlation Parameters:
##       estimate    san.se     wald p
## alpha 2.456858 0.2752256 79.68609 0
## 
## Returned Error Value:    0 
## Number of clusters:   111   Maximum cluster size: 4</code></pre>
</div>
</div>
<div id="penalized-regression-with-ordinal-outcomes" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Penalized Regression with Ordinal Outcomes<a href="ordinal-regression.html#penalized-regression-with-ordinal-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>The <code>ordinalgmifs</code> package fits L1-penalized regression with
<strong>ordinal</strong> outcomes.
<ul>
<li><code>ordinalNet</code> is another package that performs penalized
regression for <strong>ordinal</strong> outcomes.</li>
</ul></li>
<li>To use <code>ordinalgmifs</code>, we will use the <code>eyedisease</code> dataset in the
package.</li>
</ul>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="ordinal-regression.html#cb314-1" tabindex="-1"></a><span class="fu">library</span>(ordinalgmifs)</span></code></pre></div>
<pre><code>## Loading required package: survival</code></pre>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="ordinal-regression.html#cb316-1" tabindex="-1"></a><span class="fu">data</span>(eyedisease)</span>
<span id="cb316-2"><a href="ordinal-regression.html#cb316-2" tabindex="-1"></a><span class="fu">names</span>(eyedisease)</span></code></pre></div>
<pre><code>##  [1] &quot;rme&quot;  &quot;lme&quot;  &quot;rre&quot;  &quot;lre&quot;  &quot;riop&quot; &quot;liop&quot; &quot;age&quot;  &quot;diab&quot; &quot;gh&quot;   &quot;sbp&quot; 
## [11] &quot;dbp&quot;  &quot;bmi&quot;  &quot;pr&quot;   &quot;sex&quot;  &quot;prot&quot; &quot;dose&quot; &quot;rerl&quot; &quot;lerl&quot; &quot;id&quot;</code></pre>
<ul>
<li>A variable of interest is <code>rerl</code>.
<ul>
<li><p>This is right eye severity of retinopathy.</p></li>
<li><p>This is an <strong>ordered factor</strong> with levels “None”, “Mild”,
“Moderate”, and “Proliferative”.</p></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="ordinal-regression.html#cb318-1" tabindex="-1"></a><span class="fu">table</span>( eyedisease<span class="sc">$</span>rerl )</span></code></pre></div>
<pre><code>## 
##          None          Mild      Moderate Proliferative 
##           275           270           128            47</code></pre>
<hr />
<ul>
<li>To fit a <strong>penalized ordinal regression</strong> where we can penalize all
variables, use the following code:</li>
</ul>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="ordinal-regression.html#cb320-1" tabindex="-1"></a><span class="do">## Fit ordinal logistic regression with covariates </span></span>
<span id="cb320-2"><a href="ordinal-regression.html#cb320-2" tabindex="-1"></a><span class="do">## dose, prot, sex, bmi, dbp, sbp, pr, age</span></span>
<span id="cb320-3"><a href="ordinal-regression.html#cb320-3" tabindex="-1"></a>eye.fit <span class="ot">&lt;-</span> <span class="fu">ordinalgmifs</span>(rerl <span class="sc">~</span> <span class="dv">1</span>, <span class="at">x=</span><span class="fu">c</span>(<span class="st">&quot;dose&quot;</span>, <span class="st">&quot;prot&quot;</span>, <span class="st">&quot;sex&quot;</span>, </span>
<span id="cb320-4"><a href="ordinal-regression.html#cb320-4" tabindex="-1"></a>                        <span class="st">&quot;bmi&quot;</span>, <span class="st">&quot;dbp&quot;</span>, <span class="st">&quot;sbp&quot;</span>, <span class="st">&quot;pr&quot;</span>, <span class="st">&quot;age&quot;</span>), <span class="at">data=</span>eyedisease)</span></code></pre></div>
<ul>
<li>If we look at a <code>summary</code> of <code>eye.fit</code> it will display the best
regression coefficient estimates according to an <strong>AIC</strong> criterion:</li>
</ul>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="ordinal-regression.html#cb321-1" tabindex="-1"></a><span class="fu">summary</span>(eye.fit)</span></code></pre></div>
<pre><code>## Cumulative model using a  logit  link 
## at step    =  1339 
## logLik     =  -813.1043 
## AIC        =  10358.21 
## BIC        =  22327.05</code></pre>
<pre><code>## (Intercept):1 (Intercept):2 (Intercept):3          dose          prot 
##    -0.5779889     1.2531085     2.9824752     0.1080000    -0.2960000 
##           sex           bmi           dbp           sbp            pr 
##     0.0000000    -0.1410000    -0.2350000    -0.4370000    -0.0720000 
##           age 
##     0.0500000</code></pre>
<ul>
<li>According to <strong>AIC</strong>, all variables are selected except for <code>sex</code>.</li>
</ul>
<hr />
<ul>
<li><p>To get the “full path” of coefficient solutions, look at the <code>beta</code>
component of <code>eye.fit</code>.</p></li>
<li><p><code>eye.fit$beta</code> is a 1453 x 8 matrix.</p>
<ul>
<li><p>Row <span class="math inline">\(k\)</span> of <code>eye.fit$beta</code> has the value of the regression
coefficients at step <span class="math inline">\(k\)</span></p></li>
<li><p>Row <span class="math inline">\(k\)</span> of <code>eye.fit$alpha</code> has the value of the intercept
coefficient at step <span class="math inline">\(k\)</span></p></li>
</ul></li>
</ul>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="ordinal-regression.html#cb324-1" tabindex="-1"></a><span class="fu">dim</span>(eye.fit<span class="sc">$</span>beta)</span></code></pre></div>
<pre><code>## [1] 1453    8</code></pre>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="ordinal-regression.html#cb326-1" tabindex="-1"></a><span class="do">## Look at an &quot;early&quot; row of eye.fit$beta</span></span>
<span id="cb326-2"><a href="ordinal-regression.html#cb326-2" tabindex="-1"></a><span class="do">## Most of the coefficients here should be zero</span></span>
<span id="cb326-3"><a href="ordinal-regression.html#cb326-3" tabindex="-1"></a>eye.fit<span class="sc">$</span>beta[<span class="dv">10</span>,]</span></code></pre></div>
<pre><code>##  dose  prot   sex   bmi   dbp   sbp    pr   age 
##  0.00  0.00  0.00  0.00  0.00 -0.01  0.00  0.00</code></pre>
<ul>
<li>If we look at a later row, we should have more non-zero coefficients</li>
</ul>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="ordinal-regression.html#cb328-1" tabindex="-1"></a>eye.fit<span class="sc">$</span>beta[<span class="dv">800</span>,]</span></code></pre></div>
<pre><code>##   dose   prot    sex    bmi    dbp    sbp     pr    age 
##  0.000 -0.202  0.000 -0.022 -0.188 -0.388  0.000  0.000</code></pre>
<ul>
<li>The <code>model.select</code> component gives the row index of the <strong>selected
model</strong></li>
</ul>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="ordinal-regression.html#cb330-1" tabindex="-1"></a>eye.fit<span class="sc">$</span>model.select </span></code></pre></div>
<pre><code>## [1] 1339</code></pre>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="ordinal-regression.html#cb332-1" tabindex="-1"></a>eye.fit<span class="sc">$</span>beta[eye.fit<span class="sc">$</span>model.select,]</span></code></pre></div>
<pre><code>##   dose   prot    sex    bmi    dbp    sbp     pr    age 
##  0.108 -0.296  0.000 -0.141 -0.235 -0.437 -0.072  0.050</code></pre>
<hr />
<ul>
<li>You can plot the “lasso path” for the regression coefficient
estimates:</li>
</ul>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="ordinal-regression.html#cb334-1" tabindex="-1"></a><span class="fu">plot</span>( eye.fit )</span></code></pre></div>
<p><img src="07-OrdinalRegression_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-heagerty1996" class="csl-entry">
Heagerty, Patrick J, and Scott L Zeger. 1996. <span>“Marginal Regression Models for Clustered Ordinal Measurements.”</span> <em>Journal of the American Statistical Association</em> 91 (435): 1024–36.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="risk-prediction2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="extra-topics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
